#!/usr/bin/env -S deno run -A

// generates src/events.ts

import {
	type EventDefinition,
	fetchProtocol,
	humanToPascal,
	translateValueType,
	writeAndFormat,
} from "./common.ts";

const proto = await fetchProtocol();

const Masks: Record<string, number> = {
	General: 0,
	Config: 1,
	Scenes: 2,
	Inputs: 3,
	Transitions: 4,
	Filters: 5,
	Outputs: 6,
	SceneItems: 7,
	MediaInputs: 8,
	Vendors: 9,
	Ui: 10,
	InputVolumeMeters: 16,
	InputActiveStateChanged: 17,
	InputShowStateChanged: 18,
	SceneItemTransformChanged: 19,
} as const;

export type Event = {
	name: string;
	description: string;
	category: string;
	mask: number;
	fields: Field[];
};

export type Field = {
	name: string;
	description: string;
	type: string;
};

function translate(event: EventDefinition): Event {
	return {
		name: event.eventType,
		description: event.description,
		category: humanToPascal(event.category),
		mask: Masks[humanToPascal(event.category)],
		fields: event.dataFields.map((field) => ({
			name: field.valueName,
			description: field.valueDescription,
			type: translateValueType(field.valueType),
		})),
	};
}

const special: Record<
	string,
	[((ev: Event) => void)?, (Record<string, (ev: Field) => void>)?]
> = {
	InputVolumeMeters: [(ev) => {
		ev.mask = Masks.InputVolumeMeters;
	}],
	InputActiveStateChanged: [(ev) => {
		ev.mask = Masks.InputActiveStateChanged;
	}],
	InputShowStateChanged: [(ev) => {
		ev.mask = Masks.InputShowStateChanged;
	}],
	SceneItemTransformChanged: [(ev) => {
		ev.mask = Masks.SceneItemTransformChanged;
	}, {
		sceneItemTransform: (field) =>
			field.type = `{
	sourceWidth: number;
	sourceHeight: number;
	positionX: number;
	positionY: number;
	rotation: number;
	scaleX: number;
	scaleY: number;
	width: number;
	height: number;
	alignment: number;
	boundsType: number;
	boundsAlignment: number;
	boundsWidth: number;
	boundsHeight: number;
	cropLeft: number;
	cropRight: number;
	cropTop: number;
	cropBottom: number;
	cropToBounds: boolean;
}`,
	}],
	SceneListChanged: [undefined, {
		scenes: (field) =>
			field.type =
				"{\nsceneName: string;\nsceneUuid: string;\nsceneIndex: number;\n}[]",
	}],
	SceneItemListReindexed: [undefined, {
		sceneItems: (field) =>
			field.type = "{\nsceneItemId: number;\nsceneItemInedx: number;\n}",
	}],
} as const;

const lintObjectAllow = [
	"CustomEvent.eventData",
	"VendorEvent.eventData",
].map((n) => n.split(".") as [string, string]);
function lint(event: Event) {
	event.fields.forEach((field) => {
		const objectAllow = lintObjectAllow.find((check) =>
			event.name === check[0] && field.name === check[1]
		);
		// most instances of Object are actually typed but just not documented
		if (
			!objectAllow && (field.type === "object" || field.type === "object[]")
		) {
			console.log(`lint: ${event.name}.${field.name} uses type ${field.type}`);
		}
	});
}

function code(event: Event): string {
	let gen = "";
	if (event.fields.length > 0) {
		gen +=
			`/** Payload for {@link ${event.name}} */\nexport type ${event.name}Payload = {${
				event.fields.map((field) =>
					`/** ${field.description} */\n${field.name}: ${field.type};\n`
				).join("")
			}};\n\n`;
	}
	const payload = event.fields.length > 0
		? `${event.name}Payload`
		: "Record<PropertyKey, never>";
	gen +=
		`/** ${event.description} */\nexport const ${event.name}: ObsEvent<${payload}> = new ObsEvent<${payload}>("${event.name}", 1 << ${event.mask});\n\n`;
	return gen;
}

const prelude = `// This file is @generated by scripts/events.ts

export class ObsEvent<Payload> {
	type: string;
	mask: number;
	constructor(type: string, mask: number) {
		this.type = type;
		this.mask = mask;
	}
}\n\n`;

export function getEvents(): Event[] {
	const events = proto.events.map(translate);
	events.forEach((event) => {
		if (special[event.name]) {
			const [fix, fields] = special[event.name];
			if (fix) fix(event);
			if (fields) {
				Object.entries(fields).forEach(([name, callback]) => {
					event.fields.forEach((field) =>
						field.name === name && callback(field)
					);
				});
			}
		}
	});
	events.sort((a, b) => (a.name > b.name) ? 1 : -1);
	return events;
}

if (import.meta.main) {
	const events = getEvents();
	events.forEach(lint);
	const generated = events.map(code).join("");
	await writeAndFormat("events.ts", `${prelude}${generated}`);
}
