#!/usr/bin/env -S deno run -A

// generates src/requests.ts

import {
	fetchProtocol,
	humanToPascal,
	type RequestDefinition,
	translateValueType,
	writeAndFormat,
} from "./common.ts";

const proto = await fetchProtocol();

export type Request = {
	name: string;
	description: string;
	category: string;
	requestFields: RequestField[];
	responseFields: ResponseField[];
};

export type RequestField = {
	name: string;
	type: string;
	description: string;
	optional: boolean;
};

export type ResponseField = {
	name: string;
	type: string;
	description: string;
};

function translate(request: RequestDefinition): Request {
	return {
		name: request.requestType,
		description: request.description,
		category: humanToPascal(request.category),
		requestFields: request.requestFields.map((field) => ({
			name: field.valueName,
			type: translateValueType(field.valueType),
			description: field.valueDescription,
			optional: field.valueOptional,
		})),
		responseFields: request.responseFields.map((field) => ({
			name: field.valueName,
			type: translateValueType(field.valueType),
			description: field.valueDescription,
		})),
	};
}

const special: Record<
	string,
	[
		((ev: Request) => void)?,
		(Record<string, (ev: RequestField) => void>)?,
		(Record<string, (ev: ResponseField) => void>)?,
	]
> = {
	TriggerHotkeyByKeySequence: [(request) => {
		request.requestFields = request.requestFields.filter((field) =>
			!field.name.includes(".")
		);
	}, {
		keyModifiers: (field) =>
			field.type = `{
				/** Press Shift */
				shift?: boolean;
				/** Press CTRL */
				control?: boolean;
				/** Press ALT */
				alt?: boolean;
				/** Press CMD (Mac) */
				command?: boolean;
			}`,
	}],
};

const lintObjectAllow = [
	"BroadcastCustomEvent.eventData",
	"CallVendorRequest.requestData",
	"CallVendorRequest.responseData",
].map((n) => n.split(".") as [string, string]);
function lint(request: Request) {
	[...request.requestFields, ...request.responseFields].forEach((field) => {
		const objectAllow = lintObjectAllow.find((check) =>
			request.name === check[0] && field.name === check[1]
		);
		// most instances of Object are actually typed but just not documented
		if (
			!objectAllow && (field.type === "object" || field.type === "object[]")
		) {
			console.log(
				`lint: ${request.name}.${field.name} uses type ${field.type}`,
			);
		}
	});
}

function requestsCode(request: Request) {
	let gen = "";
	if (request.requestFields.length > 0) {
		gen +=
			`/** Request for {@link ${request.name}} */\nexport type ${request.name}Request = {${
				request.requestFields.map((field) =>
					`/** ${field.description} */
					${field.name}${field.optional ? "?" : ""}: ${field.type};\n`
				).join("")
			}};\n\n`;
	}
	if (request.responseFields.length > 0) {
		gen +=
			`/** Response for {@link ${request.name}} */\nexport type ${request.name}Response = {${
				request.responseFields.map((field) =>
					`/** ${field.description} */
					${field.name}: ${field.type};\n`
				).join("")
			}};\n\n`;
	}
	const payload = `${request.requestFields.length > 0
		? `${request.name}Request`
		: "undefined"}, ${
			request.responseFields.length > 0
				? `${request.name}Response`
				: "undefined"
		}`;
	gen +=
		`/** ${request.description} */\nexport const ${request.name}: ObsRequest<${payload}> = new ObsRequest<${payload}>("${request.name}");\n\n`;
	return gen;
}

const prelude = `// This file is @generated by scripts/requests.ts

export class ObsRequest<Request, Response> {
	type: string;
	constructor(name: string) {
		this.type = name;
	}
}\n\n`;

export function getRequests(): Request[] {
	const requests = proto.requests.map(translate);
	requests.forEach((request) => {
		if (special[request.name]) {
			const [fix, requestFields, responseFields] = special[request.name];
			if (fix) fix(request);
			if (requestFields) {
				Object.entries(requestFields).forEach(([name, callback]) => {
					request.requestFields.forEach((field) =>
						field.name === name && callback(field)
					);
				});
			}
			if (responseFields) {
				Object.entries(responseFields).forEach(([name, callback]) => {
					request.responseFields.forEach((field) =>
						field.name === name && callback(field)
					);
				});
			}
		}
	});
	requests.sort((a, b) => (a.name > b.name) ? 1 : -1);
	return requests;
}

if (import.meta.main) {
	const requests = getRequests();
	requests.forEach(lint);
	const generated = requests.map(requestsCode).join("");
	await writeAndFormat("requests.ts", `${prelude}${generated}`);
}
