#!/usr/bin/env -S deno run -A

// generates src/wrappers/*.ts

import { getRequests, type Request } from "./requests.ts";
import { type Event, getEvents } from "./events.ts";
import {
	pascalToKebab,
	uncapitalizeFirst,
	writeAndFormat,
} from "./common.ts";

const events = getEvents();
const requests = getRequests();

const categories = [
	...new Set([
		...events.map((event) => event.category),
		...requests.map((request) => request.category),
	]),
];

const wrapperClasses: Record<string, string[]> = {};
const wrapperRequestImports: Record<string, string[]> = {};
const wrapperRequestTypes: Record<string, string[]> = {};
const wrapperEventImports: Record<string, string[]> = {};
const wrapperEventTypes: Record<string, string[]> = {};

for (const category of categories) {
	wrapperClasses[category] = [];
	wrapperRequestImports[category] = [];
	wrapperRequestTypes[category] = [];
	wrapperEventImports[category] = [];
	wrapperEventTypes[category] = [];
}

function requestMember(request: Request) {
	const gen = `/** ${request.description} */\n${
		uncapitalizeFirst(request.name)
	}(${
		request.requestFields.length > 0 ? `request: ${request.name}Request` : ""
	}): Promise<${
		request.responseFields.length > 0 ? `${request.name}Response` : "void"
	} > {
		return this.obs.call(${request.name}, ${
		request.requestFields.length > 0 ? `request` : "undefined"
	});
	}`;
	wrapperClasses[request.category].push(gen);
	wrapperRequestImports[request.category].push(request.name);
	if (request.requestFields.length > 0) {
		wrapperRequestTypes[request.category].push(`${request.name}Request`);
	}
	if (request.responseFields.length > 0) {
		wrapperRequestTypes[request.category].push(`${request.name}Response`);
	}
}

function eventMember(event: Event) {
	const gen = `/** ${event.description} */\non${event.name}(callback: (${
		event.fields.length > 0 ? `payload: ${event.name}Payload` : ""
	}) => void): Promise<void> {
		return this.obs.subscribe(${event.name}, callback);
	}`;
	wrapperClasses[event.category].push(gen);
	wrapperEventImports[event.category].push(event.name);
	if (event.fields.length > 0) {
		wrapperEventTypes[event.category].push(`${event.name}Payload`);
	}
}

function code(category: string): string {
	const members = wrapperClasses[category];
	const requestImports = wrapperRequestImports[category];
	const requestTypes = wrapperRequestTypes[category];
	const eventImports = wrapperEventImports[category];
	const eventTypes = wrapperEventTypes[category];
	let gen = "";
	gen += "// This file is @generated by scripts/wrappers.ts\n\n";
	gen += `import type { ObsWs } from "../client.ts";\nimport { ${
		requestImports.join(", ")
	} } from "../requests.ts";\nimport type { ${
		requestTypes.join(", ")
	} } from "../requests.ts";\nimport { ${
		eventImports.join(", ")
	} } from "../events.ts";\nimport type { ${
		eventTypes.join(", ")
	} } from "../events.ts";\n\n`;
	gen += `export class Obs${category} {
		obs: ObsWs;
		constructor(obs: ObsWs) {
			this.obs = obs;
		}

		${members.join("\n\n")}
	}`;
	return gen;
}

requests.forEach(requestMember);
events.forEach(eventMember);
const wrappers = Object.keys(wrapperClasses).map((
	category,
) => [category, code(category)]);
for (const [category, code] of wrappers) {
	await writeAndFormat(`wrappers/${pascalToKebab(category)}.ts`, code);
}
