// This file is @generated by scripts/wrappers.ts

import type { ObsWs } from "../client.ts";
import {
	CreateProfile,
	CreateSceneCollection,
	GetPersistentData,
	GetProfileList,
	GetProfileParameter,
	GetRecordDirectory,
	GetSceneCollectionList,
	GetStreamServiceSettings,
	GetVideoSettings,
	RemoveProfile,
	SetCurrentProfile,
	SetCurrentSceneCollection,
	SetPersistentData,
	SetProfileParameter,
	SetRecordDirectory,
	SetStreamServiceSettings,
	SetVideoSettings,
} from "../requests.ts";
import type {
	CreateProfileRequest,
	CreateSceneCollectionRequest,
	GetPersistentDataRequest,
	GetPersistentDataResponse,
	GetProfileListResponse,
	GetProfileParameterRequest,
	GetProfileParameterResponse,
	GetRecordDirectoryResponse,
	GetSceneCollectionListResponse,
	GetStreamServiceSettingsResponse,
	GetVideoSettingsResponse,
	RemoveProfileRequest,
	SetCurrentProfileRequest,
	SetCurrentSceneCollectionRequest,
	SetPersistentDataRequest,
	SetProfileParameterRequest,
	SetRecordDirectoryRequest,
	SetStreamServiceSettingsRequest,
	SetVideoSettingsRequest,
} from "../requests.ts";
import {
	CurrentProfileChanged,
	CurrentProfileChanging,
	CurrentSceneCollectionChanged,
	CurrentSceneCollectionChanging,
	ProfileListChanged,
	SceneCollectionListChanged,
} from "../events.ts";
import type {
	CurrentProfileChangedPayload,
	CurrentProfileChangingPayload,
	CurrentSceneCollectionChangedPayload,
	CurrentSceneCollectionChangingPayload,
	ProfileListChangedPayload,
	SceneCollectionListChangedPayload,
} from "../events.ts";

export class ObsConfig {
	obs: ObsWs;
	constructor(obs: ObsWs) {
		this.obs = obs;
	}

	/** Creates a new profile, switching to it in the process */
	createProfile(request: CreateProfileRequest): Promise<void> {
		return this.obs.call(CreateProfile, request);
	}

	/** Creates a new scene collection, switching to it in the process.

Note: This will block until the collection has finished changing. */
	createSceneCollection(request: CreateSceneCollectionRequest): Promise<void> {
		return this.obs.call(CreateSceneCollection, request);
	}

	/** Gets the value of a "slot" from the selected persistent data realm. */
	getPersistentData(
		request: GetPersistentDataRequest,
	): Promise<GetPersistentDataResponse> {
		return this.obs.call(GetPersistentData, request);
	}

	/** Gets an array of all profiles */
	getProfileList(): Promise<GetProfileListResponse> {
		return this.obs.call(GetProfileList, undefined);
	}

	/** Gets a parameter from the current profile's configuration. */
	getProfileParameter(
		request: GetProfileParameterRequest,
	): Promise<GetProfileParameterResponse> {
		return this.obs.call(GetProfileParameter, request);
	}

	/** Gets the current directory that the record output is set to. */
	getRecordDirectory(): Promise<GetRecordDirectoryResponse> {
		return this.obs.call(GetRecordDirectory, undefined);
	}

	/** Gets an array of all scene collections */
	getSceneCollectionList(): Promise<GetSceneCollectionListResponse> {
		return this.obs.call(GetSceneCollectionList, undefined);
	}

	/** Gets the current stream service settings (stream destination). */
	getStreamServiceSettings(): Promise<GetStreamServiceSettingsResponse> {
		return this.obs.call(GetStreamServiceSettings, undefined);
	}

	/** Gets the current video settings.

Note: To get the true FPS value, divide the FPS numerator by the FPS denominator. Example: `60000/1001` */
	getVideoSettings(): Promise<GetVideoSettingsResponse> {
		return this.obs.call(GetVideoSettings, undefined);
	}

	/** Removes a profile. If the current profile is chosen, it will change to a different profile first. */
	removeProfile(request: RemoveProfileRequest): Promise<void> {
		return this.obs.call(RemoveProfile, request);
	}

	/** Switches to a profile. */
	setCurrentProfile(request: SetCurrentProfileRequest): Promise<void> {
		return this.obs.call(SetCurrentProfile, request);
	}

	/** Switches to a scene collection.

Note: This will block until the collection has finished changing. */
	setCurrentSceneCollection(
		request: SetCurrentSceneCollectionRequest,
	): Promise<void> {
		return this.obs.call(SetCurrentSceneCollection, request);
	}

	/** Sets the value of a "slot" from the selected persistent data realm. */
	setPersistentData(request: SetPersistentDataRequest): Promise<void> {
		return this.obs.call(SetPersistentData, request);
	}

	/** Sets the value of a parameter in the current profile's configuration. */
	setProfileParameter(request: SetProfileParameterRequest): Promise<void> {
		return this.obs.call(SetProfileParameter, request);
	}

	/** Sets the current directory that the record output writes files to. */
	setRecordDirectory(request: SetRecordDirectoryRequest): Promise<void> {
		return this.obs.call(SetRecordDirectory, request);
	}

	/** Sets the current stream service settings (stream destination).

Note: Simple RTMP settings can be set with type `rtmp_custom` and the settings fields `server` and `key`. */
	setStreamServiceSettings(
		request: SetStreamServiceSettingsRequest,
	): Promise<void> {
		return this.obs.call(SetStreamServiceSettings, request);
	}

	/** Sets the current video settings.

Note: Fields must be specified in pairs. For example, you cannot set only `baseWidth` without needing to specify `baseHeight`. */
	setVideoSettings(request: SetVideoSettingsRequest): Promise<void> {
		return this.obs.call(SetVideoSettings, request);
	}

	/** The current profile has changed. */
	onCurrentProfileChanged(
		callback: (payload: CurrentProfileChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(CurrentProfileChanged, callback);
	}

	/** The current profile has begun changing. */
	onCurrentProfileChanging(
		callback: (payload: CurrentProfileChangingPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(CurrentProfileChanging, callback);
	}

	/** The current scene collection has changed.

Note: If polling has been paused during `CurrentSceneCollectionChanging`, this is the que to restart polling. */
	onCurrentSceneCollectionChanged(
		callback: (payload: CurrentSceneCollectionChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(CurrentSceneCollectionChanged, callback);
	}

	/** The current scene collection has begun changing.

Note: We recommend using this event to trigger a pause of all polling requests, as performing any requests during a
scene collection change is considered undefined behavior and can cause crashes! */
	onCurrentSceneCollectionChanging(
		callback: (payload: CurrentSceneCollectionChangingPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(CurrentSceneCollectionChanging, callback);
	}

	/** The profile list has changed. */
	onProfileListChanged(
		callback: (payload: ProfileListChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(ProfileListChanged, callback);
	}

	/** The scene collection list has changed. */
	onSceneCollectionListChanged(
		callback: (payload: SceneCollectionListChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SceneCollectionListChanged, callback);
	}
}
