// This file is @generated by scripts/wrappers.ts

import type { ObsWs } from "../client.ts";
import {
	CreateSourceFilter,
	GetSourceFilter,
	GetSourceFilterDefaultSettings,
	GetSourceFilterKindList,
	GetSourceFilterList,
	RemoveSourceFilter,
	SetSourceFilterEnabled,
	SetSourceFilterIndex,
	SetSourceFilterName,
	SetSourceFilterSettings,
} from "../requests.ts";
import type {
	CreateSourceFilterRequest,
	GetSourceFilterDefaultSettingsRequest,
	GetSourceFilterDefaultSettingsResponse,
	GetSourceFilterKindListResponse,
	GetSourceFilterListRequest,
	GetSourceFilterListResponse,
	GetSourceFilterRequest,
	GetSourceFilterResponse,
	RemoveSourceFilterRequest,
	SetSourceFilterEnabledRequest,
	SetSourceFilterIndexRequest,
	SetSourceFilterNameRequest,
	SetSourceFilterSettingsRequest,
} from "../requests.ts";
import {
	SourceFilterCreated,
	SourceFilterEnableStateChanged,
	SourceFilterListReindexed,
	SourceFilterNameChanged,
	SourceFilterRemoved,
	SourceFilterSettingsChanged,
} from "../events.ts";
import type {
	SourceFilterCreatedPayload,
	SourceFilterEnableStateChangedPayload,
	SourceFilterListReindexedPayload,
	SourceFilterNameChangedPayload,
	SourceFilterRemovedPayload,
	SourceFilterSettingsChangedPayload,
} from "../events.ts";

export class ObsFilters {
	obs: ObsWs;
	constructor(obs: ObsWs) {
		this.obs = obs;
	}

	/** Creates a new filter, adding it to the specified source. */
	createSourceFilter(request: CreateSourceFilterRequest): Promise<void> {
		return this.obs.call(CreateSourceFilter, request);
	}

	/** Gets the info for a specific source filter. */
	getSourceFilter(
		request: GetSourceFilterRequest,
	): Promise<GetSourceFilterResponse> {
		return this.obs.call(GetSourceFilter, request);
	}

	/** Gets the default settings for a filter kind. */
	getSourceFilterDefaultSettings(
		request: GetSourceFilterDefaultSettingsRequest,
	): Promise<GetSourceFilterDefaultSettingsResponse> {
		return this.obs.call(GetSourceFilterDefaultSettings, request);
	}

	/** Gets an array of all available source filter kinds.

Similar to `GetInputKindList` */
	getSourceFilterKindList(): Promise<GetSourceFilterKindListResponse> {
		return this.obs.call(GetSourceFilterKindList, undefined);
	}

	/** Gets an array of all of a source's filters. */
	getSourceFilterList(
		request: GetSourceFilterListRequest,
	): Promise<GetSourceFilterListResponse> {
		return this.obs.call(GetSourceFilterList, request);
	}

	/** Removes a filter from a source. */
	removeSourceFilter(request: RemoveSourceFilterRequest): Promise<void> {
		return this.obs.call(RemoveSourceFilter, request);
	}

	/** Sets the enable state of a source filter. */
	setSourceFilterEnabled(
		request: SetSourceFilterEnabledRequest,
	): Promise<void> {
		return this.obs.call(SetSourceFilterEnabled, request);
	}

	/** Sets the index position of a filter on a source. */
	setSourceFilterIndex(request: SetSourceFilterIndexRequest): Promise<void> {
		return this.obs.call(SetSourceFilterIndex, request);
	}

	/** Sets the name of a source filter (rename). */
	setSourceFilterName(request: SetSourceFilterNameRequest): Promise<void> {
		return this.obs.call(SetSourceFilterName, request);
	}

	/** Sets the settings of a source filter. */
	setSourceFilterSettings(
		request: SetSourceFilterSettingsRequest,
	): Promise<void> {
		return this.obs.call(SetSourceFilterSettings, request);
	}

	/** A filter has been added to a source. */
	onSourceFilterCreated(
		callback: (payload: SourceFilterCreatedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SourceFilterCreated, callback);
	}

	/** A source filter's enable state has changed. */
	onSourceFilterEnableStateChanged(
		callback: (payload: SourceFilterEnableStateChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SourceFilterEnableStateChanged, callback);
	}

	/** A source's filter list has been reindexed. */
	onSourceFilterListReindexed(
		callback: (payload: SourceFilterListReindexedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SourceFilterListReindexed, callback);
	}

	/** The name of a source filter has changed. */
	onSourceFilterNameChanged(
		callback: (payload: SourceFilterNameChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SourceFilterNameChanged, callback);
	}

	/** A filter has been removed from a source. */
	onSourceFilterRemoved(
		callback: (payload: SourceFilterRemovedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SourceFilterRemoved, callback);
	}

	/** An source filter's settings have changed (been updated). */
	onSourceFilterSettingsChanged(
		callback: (payload: SourceFilterSettingsChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SourceFilterSettingsChanged, callback);
	}
}
