// This file is @generated by scripts/wrappers.ts

import type { ObsWs } from "../client.ts";
import {
	BroadcastCustomEvent,
	CallVendorRequest,
	GetHotkeyList,
	GetStats,
	GetVersion,
	Sleep,
	TriggerHotkeyByKeySequence,
	TriggerHotkeyByName,
} from "../requests.ts";
import type {
	BroadcastCustomEventRequest,
	CallVendorRequestRequest,
	CallVendorRequestResponse,
	GetHotkeyListResponse,
	GetStatsResponse,
	GetVersionResponse,
	SleepRequest,
	TriggerHotkeyByKeySequenceRequest,
	TriggerHotkeyByNameRequest,
} from "../requests.ts";
import { CustomEvent, ExitStarted, VendorEvent } from "../events.ts";
import type { CustomEventPayload, VendorEventPayload } from "../events.ts";

export class ObsGeneral {
	obs: ObsWs;
	constructor(obs: ObsWs) {
		this.obs = obs;
	}

	/** Broadcasts a `CustomEvent` to all WebSocket clients. Receivers are clients which are identified and subscribed. */
	broadcastCustomEvent(request: BroadcastCustomEventRequest): Promise<void> {
		return this.obs.call(BroadcastCustomEvent, request);
	}

	/** Call a request registered to a vendor.

A vendor is a unique name registered by a third-party plugin or script, which allows for custom requests and events to be added to obs-websocket.
If a plugin or script implements vendor requests or events, documentation is expected to be provided with them. */
	callVendorRequest(
		request: CallVendorRequestRequest,
	): Promise<CallVendorRequestResponse> {
		return this.obs.call(CallVendorRequest, request);
	}

	/** Gets an array of all hotkey names in OBS.

Note: Hotkey functionality in obs-websocket comes as-is, and we do not guarantee support if things are broken. In 9/10 usages of hotkey requests, there exists a better, more reliable method via other requests. */
	getHotkeyList(): Promise<GetHotkeyListResponse> {
		return this.obs.call(GetHotkeyList, undefined);
	}

	/** Gets statistics about OBS, obs-websocket, and the current session. */
	getStats(): Promise<GetStatsResponse> {
		return this.obs.call(GetStats, undefined);
	}

	/** Gets data about the current plugin and RPC version. */
	getVersion(): Promise<GetVersionResponse> {
		return this.obs.call(GetVersion, undefined);
	}

	/** Sleeps for a time duration or number of frames. Only available in request batches with types `SERIAL_REALTIME` or `SERIAL_FRAME`. */
	sleep(request: SleepRequest): Promise<void> {
		return this.obs.call(Sleep, request);
	}

	/** Triggers a hotkey using a sequence of keys.

Note: Hotkey functionality in obs-websocket comes as-is, and we do not guarantee support if things are broken. In 9/10 usages of hotkey requests, there exists a better, more reliable method via other requests. */
	triggerHotkeyByKeySequence(
		request: TriggerHotkeyByKeySequenceRequest,
	): Promise<void> {
		return this.obs.call(TriggerHotkeyByKeySequence, request);
	}

	/** Triggers a hotkey using its name. See `GetHotkeyList`.

Note: Hotkey functionality in obs-websocket comes as-is, and we do not guarantee support if things are broken. In 9/10 usages of hotkey requests, there exists a better, more reliable method via other requests. */
	triggerHotkeyByName(request: TriggerHotkeyByNameRequest): Promise<void> {
		return this.obs.call(TriggerHotkeyByName, request);
	}

	/** Custom event emitted by `BroadcastCustomEvent`. */
	onCustomEvent(
		callback: (payload: CustomEventPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(CustomEvent, callback);
	}

	/** OBS has begun the shutdown process. */
	onExitStarted(callback: () => void): Promise<void> {
		return this.obs.subscribe(ExitStarted, callback);
	}

	/** An event has been emitted from a vendor.

A vendor is a unique name registered by a third-party plugin or script, which allows for custom requests and events to be added to obs-websocket.
If a plugin or script implements vendor requests or events, documentation is expected to be provided with them. */
	onVendorEvent(
		callback: (payload: VendorEventPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(VendorEvent, callback);
	}
}
