// This file is @generated by scripts/wrappers.ts

import type { ObsWs } from "../client.ts";
import {
	CreateInput,
	GetInputAudioBalance,
	GetInputAudioMonitorType,
	GetInputAudioSyncOffset,
	GetInputAudioTracks,
	GetInputDefaultSettings,
	GetInputDeinterlaceFieldOrder,
	GetInputDeinterlaceMode,
	GetInputKindList,
	GetInputList,
	GetInputMute,
	GetInputPropertiesListPropertyItems,
	GetInputSettings,
	GetInputVolume,
	GetSpecialInputs,
	PressInputPropertiesButton,
	RemoveInput,
	SetInputAudioBalance,
	SetInputAudioMonitorType,
	SetInputAudioSyncOffset,
	SetInputAudioTracks,
	SetInputDeinterlaceFieldOrder,
	SetInputDeinterlaceMode,
	SetInputMute,
	SetInputName,
	SetInputSettings,
	SetInputVolume,
	ToggleInputMute,
} from "../requests.ts";
import type {
	CreateInputRequest,
	CreateInputResponse,
	GetInputAudioBalanceRequest,
	GetInputAudioBalanceResponse,
	GetInputAudioMonitorTypeRequest,
	GetInputAudioMonitorTypeResponse,
	GetInputAudioSyncOffsetRequest,
	GetInputAudioSyncOffsetResponse,
	GetInputAudioTracksRequest,
	GetInputAudioTracksResponse,
	GetInputDefaultSettingsRequest,
	GetInputDefaultSettingsResponse,
	GetInputDeinterlaceFieldOrderRequest,
	GetInputDeinterlaceFieldOrderResponse,
	GetInputDeinterlaceModeRequest,
	GetInputDeinterlaceModeResponse,
	GetInputKindListRequest,
	GetInputKindListResponse,
	GetInputListRequest,
	GetInputListResponse,
	GetInputMuteRequest,
	GetInputMuteResponse,
	GetInputPropertiesListPropertyItemsRequest,
	GetInputPropertiesListPropertyItemsResponse,
	GetInputSettingsRequest,
	GetInputSettingsResponse,
	GetInputVolumeRequest,
	GetInputVolumeResponse,
	GetSpecialInputsResponse,
	PressInputPropertiesButtonRequest,
	RemoveInputRequest,
	SetInputAudioBalanceRequest,
	SetInputAudioMonitorTypeRequest,
	SetInputAudioSyncOffsetRequest,
	SetInputAudioTracksRequest,
	SetInputDeinterlaceFieldOrderRequest,
	SetInputDeinterlaceModeRequest,
	SetInputMuteRequest,
	SetInputNameRequest,
	SetInputSettingsRequest,
	SetInputVolumeRequest,
	ToggleInputMuteRequest,
	ToggleInputMuteResponse,
} from "../requests.ts";
import {
	InputActiveStateChanged,
	InputAudioBalanceChanged,
	InputAudioMonitorTypeChanged,
	InputAudioSyncOffsetChanged,
	InputAudioTracksChanged,
	InputCreated,
	InputMuteStateChanged,
	InputNameChanged,
	InputRemoved,
	InputSettingsChanged,
	InputShowStateChanged,
	InputVolumeChanged,
	InputVolumeMeters,
} from "../events.ts";
import type {
	InputActiveStateChangedPayload,
	InputAudioBalanceChangedPayload,
	InputAudioMonitorTypeChangedPayload,
	InputAudioSyncOffsetChangedPayload,
	InputAudioTracksChangedPayload,
	InputCreatedPayload,
	InputMuteStateChangedPayload,
	InputNameChangedPayload,
	InputRemovedPayload,
	InputSettingsChangedPayload,
	InputShowStateChangedPayload,
	InputVolumeChangedPayload,
	InputVolumeMetersPayload,
} from "../events.ts";

export class ObsInputs {
	obs: ObsWs;
	constructor(obs: ObsWs) {
		this.obs = obs;
	}

	/** Creates a new input, adding it as a scene item to the specified scene. */
	createInput(request: CreateInputRequest): Promise<CreateInputResponse> {
		return this.obs.call(CreateInput, request);
	}

	/** Gets the audio balance of an input. */
	getInputAudioBalance(
		request: GetInputAudioBalanceRequest,
	): Promise<GetInputAudioBalanceResponse> {
		return this.obs.call(GetInputAudioBalance, request);
	}

	/** Gets the audio monitor type of an input.

The available audio monitor types are:

- `OBS_MONITORING_TYPE_NONE`
- `OBS_MONITORING_TYPE_MONITOR_ONLY`
- `OBS_MONITORING_TYPE_MONITOR_AND_OUTPUT` */
	getInputAudioMonitorType(
		request: GetInputAudioMonitorTypeRequest,
	): Promise<GetInputAudioMonitorTypeResponse> {
		return this.obs.call(GetInputAudioMonitorType, request);
	}

	/** Gets the audio sync offset of an input.

Note: The audio sync offset can be negative too! */
	getInputAudioSyncOffset(
		request: GetInputAudioSyncOffsetRequest,
	): Promise<GetInputAudioSyncOffsetResponse> {
		return this.obs.call(GetInputAudioSyncOffset, request);
	}

	/** Gets the enable state of all audio tracks of an input. */
	getInputAudioTracks(
		request: GetInputAudioTracksRequest,
	): Promise<GetInputAudioTracksResponse> {
		return this.obs.call(GetInputAudioTracks, request);
	}

	/** Gets the default settings for an input kind. */
	getInputDefaultSettings(
		request: GetInputDefaultSettingsRequest,
	): Promise<GetInputDefaultSettingsResponse> {
		return this.obs.call(GetInputDefaultSettings, request);
	}

	/** Gets the deinterlace field order of an input.

Deinterlace Field Orders:

- `OBS_DEINTERLACE_FIELD_ORDER_TOP`
- `OBS_DEINTERLACE_FIELD_ORDER_BOTTOM`

Note: Deinterlacing functionality is restricted to async inputs only. */
	getInputDeinterlaceFieldOrder(
		request: GetInputDeinterlaceFieldOrderRequest,
	): Promise<GetInputDeinterlaceFieldOrderResponse> {
		return this.obs.call(GetInputDeinterlaceFieldOrder, request);
	}

	/** Gets the deinterlace mode of an input.

Deinterlace Modes:

- `OBS_DEINTERLACE_MODE_DISABLE`
- `OBS_DEINTERLACE_MODE_DISCARD`
- `OBS_DEINTERLACE_MODE_RETRO`
- `OBS_DEINTERLACE_MODE_BLEND`
- `OBS_DEINTERLACE_MODE_BLEND_2X`
- `OBS_DEINTERLACE_MODE_LINEAR`
- `OBS_DEINTERLACE_MODE_LINEAR_2X`
- `OBS_DEINTERLACE_MODE_YADIF`
- `OBS_DEINTERLACE_MODE_YADIF_2X`

Note: Deinterlacing functionality is restricted to async inputs only. */
	getInputDeinterlaceMode(
		request: GetInputDeinterlaceModeRequest,
	): Promise<GetInputDeinterlaceModeResponse> {
		return this.obs.call(GetInputDeinterlaceMode, request);
	}

	/** Gets an array of all available input kinds in OBS. */
	getInputKindList(
		request: GetInputKindListRequest,
	): Promise<GetInputKindListResponse> {
		return this.obs.call(GetInputKindList, request);
	}

	/** Gets an array of all inputs in OBS. */
	getInputList(request: GetInputListRequest): Promise<GetInputListResponse> {
		return this.obs.call(GetInputList, request);
	}

	/** Gets the audio mute state of an input. */
	getInputMute(request: GetInputMuteRequest): Promise<GetInputMuteResponse> {
		return this.obs.call(GetInputMute, request);
	}

	/** Gets the items of a list property from an input's properties.

Note: Use this in cases where an input provides a dynamic, selectable list of items. For example, display capture, where it provides a list of available displays. */
	getInputPropertiesListPropertyItems(
		request: GetInputPropertiesListPropertyItemsRequest,
	): Promise<GetInputPropertiesListPropertyItemsResponse> {
		return this.obs.call(GetInputPropertiesListPropertyItems, request);
	}

	/** Gets the settings of an input.

Note: Does not include defaults. To create the entire settings object, overlay `inputSettings` over the `defaultInputSettings` provided by `GetInputDefaultSettings`. */
	getInputSettings(
		request: GetInputSettingsRequest,
	): Promise<GetInputSettingsResponse> {
		return this.obs.call(GetInputSettings, request);
	}

	/** Gets the current volume setting of an input. */
	getInputVolume(
		request: GetInputVolumeRequest,
	): Promise<GetInputVolumeResponse> {
		return this.obs.call(GetInputVolume, request);
	}

	/** Gets the names of all special inputs. */
	getSpecialInputs(): Promise<GetSpecialInputsResponse> {
		return this.obs.call(GetSpecialInputs, undefined);
	}

	/** Presses a button in the properties of an input.

Some known `propertyName` values are:

- `refreshnocache` - Browser source reload button

Note: Use this in cases where there is a button in the properties of an input that cannot be accessed in any other way. For example, browser sources, where there is a refresh button. */
	pressInputPropertiesButton(
		request: PressInputPropertiesButtonRequest,
	): Promise<void> {
		return this.obs.call(PressInputPropertiesButton, request);
	}

	/** Removes an existing input.

Note: Will immediately remove all associated scene items. */
	removeInput(request: RemoveInputRequest): Promise<void> {
		return this.obs.call(RemoveInput, request);
	}

	/** Sets the audio balance of an input. */
	setInputAudioBalance(request: SetInputAudioBalanceRequest): Promise<void> {
		return this.obs.call(SetInputAudioBalance, request);
	}

	/** Sets the audio monitor type of an input. */
	setInputAudioMonitorType(
		request: SetInputAudioMonitorTypeRequest,
	): Promise<void> {
		return this.obs.call(SetInputAudioMonitorType, request);
	}

	/** Sets the audio sync offset of an input. */
	setInputAudioSyncOffset(
		request: SetInputAudioSyncOffsetRequest,
	): Promise<void> {
		return this.obs.call(SetInputAudioSyncOffset, request);
	}

	/** Sets the enable state of audio tracks of an input. */
	setInputAudioTracks(request: SetInputAudioTracksRequest): Promise<void> {
		return this.obs.call(SetInputAudioTracks, request);
	}

	/** Sets the deinterlace field order of an input.

Note: Deinterlacing functionality is restricted to async inputs only. */
	setInputDeinterlaceFieldOrder(
		request: SetInputDeinterlaceFieldOrderRequest,
	): Promise<void> {
		return this.obs.call(SetInputDeinterlaceFieldOrder, request);
	}

	/** Sets the deinterlace mode of an input.

Note: Deinterlacing functionality is restricted to async inputs only. */
	setInputDeinterlaceMode(
		request: SetInputDeinterlaceModeRequest,
	): Promise<void> {
		return this.obs.call(SetInputDeinterlaceMode, request);
	}

	/** Sets the audio mute state of an input. */
	setInputMute(request: SetInputMuteRequest): Promise<void> {
		return this.obs.call(SetInputMute, request);
	}

	/** Sets the name of an input (rename). */
	setInputName(request: SetInputNameRequest): Promise<void> {
		return this.obs.call(SetInputName, request);
	}

	/** Sets the settings of an input. */
	setInputSettings(request: SetInputSettingsRequest): Promise<void> {
		return this.obs.call(SetInputSettings, request);
	}

	/** Sets the volume setting of an input. */
	setInputVolume(request: SetInputVolumeRequest): Promise<void> {
		return this.obs.call(SetInputVolume, request);
	}

	/** Toggles the audio mute state of an input. */
	toggleInputMute(
		request: ToggleInputMuteRequest,
	): Promise<ToggleInputMuteResponse> {
		return this.obs.call(ToggleInputMute, request);
	}

	/** An input's active state has changed.

When an input is active, it means it's being shown by the program feed. */
	onInputActiveStateChanged(
		callback: (payload: InputActiveStateChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(InputActiveStateChanged, callback);
	}

	/** The audio balance value of an input has changed. */
	onInputAudioBalanceChanged(
		callback: (payload: InputAudioBalanceChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(InputAudioBalanceChanged, callback);
	}

	/** The monitor type of an input has changed.

Available types are:

- `OBS_MONITORING_TYPE_NONE`
- `OBS_MONITORING_TYPE_MONITOR_ONLY`
- `OBS_MONITORING_TYPE_MONITOR_AND_OUTPUT` */
	onInputAudioMonitorTypeChanged(
		callback: (payload: InputAudioMonitorTypeChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(InputAudioMonitorTypeChanged, callback);
	}

	/** The sync offset of an input has changed. */
	onInputAudioSyncOffsetChanged(
		callback: (payload: InputAudioSyncOffsetChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(InputAudioSyncOffsetChanged, callback);
	}

	/** The audio tracks of an input have changed. */
	onInputAudioTracksChanged(
		callback: (payload: InputAudioTracksChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(InputAudioTracksChanged, callback);
	}

	/** An input has been created. */
	onInputCreated(
		callback: (payload: InputCreatedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(InputCreated, callback);
	}

	/** An input's mute state has changed. */
	onInputMuteStateChanged(
		callback: (payload: InputMuteStateChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(InputMuteStateChanged, callback);
	}

	/** The name of an input has changed. */
	onInputNameChanged(
		callback: (payload: InputNameChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(InputNameChanged, callback);
	}

	/** An input has been removed. */
	onInputRemoved(
		callback: (payload: InputRemovedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(InputRemoved, callback);
	}

	/** An input's settings have changed (been updated).

Note: On some inputs, changing values in the properties dialog will cause an immediate update. Pressing the "Cancel" button will revert the settings, resulting in another event being fired. */
	onInputSettingsChanged(
		callback: (payload: InputSettingsChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(InputSettingsChanged, callback);
	}

	/** An input's show state has changed.

When an input is showing, it means it's being shown by the preview or a dialog. */
	onInputShowStateChanged(
		callback: (payload: InputShowStateChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(InputShowStateChanged, callback);
	}

	/** An input's volume level has changed. */
	onInputVolumeChanged(
		callback: (payload: InputVolumeChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(InputVolumeChanged, callback);
	}

	/** A high-volume event providing volume levels of all active inputs every 50 milliseconds. */
	onInputVolumeMeters(
		callback: (payload: InputVolumeMetersPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(InputVolumeMeters, callback);
	}
}
