// This file is @generated by scripts/wrappers.ts

import type { ObsWs } from "../client.ts";
import {
	GetMediaInputStatus,
	OffsetMediaInputCursor,
	SetMediaInputCursor,
	TriggerMediaInputAction,
} from "../requests.ts";
import type {
	GetMediaInputStatusRequest,
	GetMediaInputStatusResponse,
	OffsetMediaInputCursorRequest,
	SetMediaInputCursorRequest,
	TriggerMediaInputActionRequest,
} from "../requests.ts";
import {
	MediaInputActionTriggered,
	MediaInputPlaybackEnded,
	MediaInputPlaybackStarted,
} from "../events.ts";
import type {
	MediaInputActionTriggeredPayload,
	MediaInputPlaybackEndedPayload,
	MediaInputPlaybackStartedPayload,
} from "../events.ts";

export class ObsMediaInputs {
	obs: ObsWs;
	constructor(obs: ObsWs) {
		this.obs = obs;
	}

	/** Gets the status of a media input.

Media States:

- `OBS_MEDIA_STATE_NONE`
- `OBS_MEDIA_STATE_PLAYING`
- `OBS_MEDIA_STATE_OPENING`
- `OBS_MEDIA_STATE_BUFFERING`
- `OBS_MEDIA_STATE_PAUSED`
- `OBS_MEDIA_STATE_STOPPED`
- `OBS_MEDIA_STATE_ENDED`
- `OBS_MEDIA_STATE_ERROR` */
	getMediaInputStatus(
		request: GetMediaInputStatusRequest,
	): Promise<GetMediaInputStatusResponse> {
		return this.obs.call(GetMediaInputStatus, request);
	}

	/** Offsets the current cursor position of a media input by the specified value.

This request does not perform bounds checking of the cursor position. */
	offsetMediaInputCursor(
		request: OffsetMediaInputCursorRequest,
	): Promise<void> {
		return this.obs.call(OffsetMediaInputCursor, request);
	}

	/** Sets the cursor position of a media input.

This request does not perform bounds checking of the cursor position. */
	setMediaInputCursor(request: SetMediaInputCursorRequest): Promise<void> {
		return this.obs.call(SetMediaInputCursor, request);
	}

	/** Triggers an action on a media input. */
	triggerMediaInputAction(
		request: TriggerMediaInputActionRequest,
	): Promise<void> {
		return this.obs.call(TriggerMediaInputAction, request);
	}

	/** An action has been performed on an input. */
	onMediaInputActionTriggered(
		callback: (payload: MediaInputActionTriggeredPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(MediaInputActionTriggered, callback);
	}

	/** A media input has finished playing. */
	onMediaInputPlaybackEnded(
		callback: (payload: MediaInputPlaybackEndedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(MediaInputPlaybackEnded, callback);
	}

	/** A media input has started playing. */
	onMediaInputPlaybackStarted(
		callback: (payload: MediaInputPlaybackStartedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(MediaInputPlaybackStarted, callback);
	}
}
