// This file is @generated by scripts/wrappers.ts

import type { ObsWs } from "../client.ts";
import {
	GetLastReplayBufferReplay,
	GetOutputList,
	GetOutputSettings,
	GetOutputStatus,
	GetReplayBufferStatus,
	GetVirtualCamStatus,
	SaveReplayBuffer,
	SetOutputSettings,
	StartOutput,
	StartReplayBuffer,
	StartVirtualCam,
	StopOutput,
	StopReplayBuffer,
	StopVirtualCam,
	ToggleOutput,
	ToggleReplayBuffer,
	ToggleVirtualCam,
} from "../requests.ts";
import type {
	GetLastReplayBufferReplayResponse,
	GetOutputListResponse,
	GetOutputSettingsRequest,
	GetOutputSettingsResponse,
	GetOutputStatusRequest,
	GetOutputStatusResponse,
	GetReplayBufferStatusResponse,
	GetVirtualCamStatusResponse,
	SetOutputSettingsRequest,
	StartOutputRequest,
	StopOutputRequest,
	ToggleOutputRequest,
	ToggleOutputResponse,
	ToggleReplayBufferResponse,
	ToggleVirtualCamResponse,
} from "../requests.ts";
import {
	RecordFileChanged,
	RecordStateChanged,
	ReplayBufferSaved,
	ReplayBufferStateChanged,
	StreamStateChanged,
	VirtualcamStateChanged,
} from "../events.ts";
import type {
	RecordFileChangedPayload,
	RecordStateChangedPayload,
	ReplayBufferSavedPayload,
	ReplayBufferStateChangedPayload,
	StreamStateChangedPayload,
	VirtualcamStateChangedPayload,
} from "../events.ts";

export class ObsOutputs {
	obs: ObsWs;
	constructor(obs: ObsWs) {
		this.obs = obs;
	}

	/** Gets the filename of the last replay buffer save file. */
	getLastReplayBufferReplay(): Promise<GetLastReplayBufferReplayResponse> {
		return this.obs.call(GetLastReplayBufferReplay, undefined);
	}

	/** Gets the list of available outputs. */
	getOutputList(): Promise<GetOutputListResponse> {
		return this.obs.call(GetOutputList, undefined);
	}

	/** Gets the settings of an output. */
	getOutputSettings(
		request: GetOutputSettingsRequest,
	): Promise<GetOutputSettingsResponse> {
		return this.obs.call(GetOutputSettings, request);
	}

	/** Gets the status of an output. */
	getOutputStatus(
		request: GetOutputStatusRequest,
	): Promise<GetOutputStatusResponse> {
		return this.obs.call(GetOutputStatus, request);
	}

	/** Gets the status of the replay buffer output. */
	getReplayBufferStatus(): Promise<GetReplayBufferStatusResponse> {
		return this.obs.call(GetReplayBufferStatus, undefined);
	}

	/** Gets the status of the virtualcam output. */
	getVirtualCamStatus(): Promise<GetVirtualCamStatusResponse> {
		return this.obs.call(GetVirtualCamStatus, undefined);
	}

	/** Saves the contents of the replay buffer output. */
	saveReplayBuffer(): Promise<void> {
		return this.obs.call(SaveReplayBuffer, undefined);
	}

	/** Sets the settings of an output. */
	setOutputSettings(request: SetOutputSettingsRequest): Promise<void> {
		return this.obs.call(SetOutputSettings, request);
	}

	/** Starts an output. */
	startOutput(request: StartOutputRequest): Promise<void> {
		return this.obs.call(StartOutput, request);
	}

	/** Starts the replay buffer output. */
	startReplayBuffer(): Promise<void> {
		return this.obs.call(StartReplayBuffer, undefined);
	}

	/** Starts the virtualcam output. */
	startVirtualCam(): Promise<void> {
		return this.obs.call(StartVirtualCam, undefined);
	}

	/** Stops an output. */
	stopOutput(request: StopOutputRequest): Promise<void> {
		return this.obs.call(StopOutput, request);
	}

	/** Stops the replay buffer output. */
	stopReplayBuffer(): Promise<void> {
		return this.obs.call(StopReplayBuffer, undefined);
	}

	/** Stops the virtualcam output. */
	stopVirtualCam(): Promise<void> {
		return this.obs.call(StopVirtualCam, undefined);
	}

	/** Toggles the status of an output. */
	toggleOutput(request: ToggleOutputRequest): Promise<ToggleOutputResponse> {
		return this.obs.call(ToggleOutput, request);
	}

	/** Toggles the state of the replay buffer output. */
	toggleReplayBuffer(): Promise<ToggleReplayBufferResponse> {
		return this.obs.call(ToggleReplayBuffer, undefined);
	}

	/** Toggles the state of the virtualcam output. */
	toggleVirtualCam(): Promise<ToggleVirtualCamResponse> {
		return this.obs.call(ToggleVirtualCam, undefined);
	}

	/** The record output has started writing to a new file. For example, when a file split happens. */
	onRecordFileChanged(
		callback: (payload: RecordFileChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(RecordFileChanged, callback);
	}

	/** The state of the record output has changed. */
	onRecordStateChanged(
		callback: (payload: RecordStateChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(RecordStateChanged, callback);
	}

	/** The replay buffer has been saved. */
	onReplayBufferSaved(
		callback: (payload: ReplayBufferSavedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(ReplayBufferSaved, callback);
	}

	/** The state of the replay buffer output has changed. */
	onReplayBufferStateChanged(
		callback: (payload: ReplayBufferStateChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(ReplayBufferStateChanged, callback);
	}

	/** The state of the stream output has changed. */
	onStreamStateChanged(
		callback: (payload: StreamStateChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(StreamStateChanged, callback);
	}

	/** The state of the virtualcam output has changed. */
	onVirtualcamStateChanged(
		callback: (payload: VirtualcamStateChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(VirtualcamStateChanged, callback);
	}
}
