// This file is @generated by scripts/wrappers.ts

import type { ObsWs } from "../client.ts";
import {
	CreateRecordChapter,
	GetRecordStatus,
	PauseRecord,
	ResumeRecord,
	SplitRecordFile,
	StartRecord,
	StopRecord,
	ToggleRecord,
	ToggleRecordPause,
} from "../requests.ts";
import type {
	CreateRecordChapterRequest,
	GetRecordStatusResponse,
	StopRecordResponse,
	ToggleRecordResponse,
} from "../requests.ts";
import {} from "../events.ts";
import type {} from "../events.ts";

export class ObsRecord {
	obs: ObsWs;
	constructor(obs: ObsWs) {
		this.obs = obs;
	}

	/** Adds a new chapter marker to the file currently being recorded.

Note: As of OBS 30.2.0, the only file format supporting this feature is Hybrid MP4. */
	createRecordChapter(request: CreateRecordChapterRequest): Promise<void> {
		return this.obs.call(CreateRecordChapter, request);
	}

	/** Gets the status of the record output. */
	getRecordStatus(): Promise<GetRecordStatusResponse> {
		return this.obs.call(GetRecordStatus, undefined);
	}

	/** Pauses the record output. */
	pauseRecord(): Promise<void> {
		return this.obs.call(PauseRecord, undefined);
	}

	/** Resumes the record output. */
	resumeRecord(): Promise<void> {
		return this.obs.call(ResumeRecord, undefined);
	}

	/** Splits the current file being recorded into a new file. */
	splitRecordFile(): Promise<void> {
		return this.obs.call(SplitRecordFile, undefined);
	}

	/** Starts the record output. */
	startRecord(): Promise<void> {
		return this.obs.call(StartRecord, undefined);
	}

	/** Stops the record output. */
	stopRecord(): Promise<StopRecordResponse> {
		return this.obs.call(StopRecord, undefined);
	}

	/** Toggles the status of the record output. */
	toggleRecord(): Promise<ToggleRecordResponse> {
		return this.obs.call(ToggleRecord, undefined);
	}

	/** Toggles pause on the record output. */
	toggleRecordPause(): Promise<void> {
		return this.obs.call(ToggleRecordPause, undefined);
	}
}
