// This file is @generated by scripts/wrappers.ts

import type { ObsWs } from "../client.ts";
import {
	CreateSceneItem,
	DuplicateSceneItem,
	GetGroupSceneItemList,
	GetSceneItemBlendMode,
	GetSceneItemEnabled,
	GetSceneItemId,
	GetSceneItemIndex,
	GetSceneItemList,
	GetSceneItemLocked,
	GetSceneItemSource,
	GetSceneItemTransform,
	RemoveSceneItem,
	SetSceneItemBlendMode,
	SetSceneItemEnabled,
	SetSceneItemIndex,
	SetSceneItemLocked,
	SetSceneItemTransform,
} from "../requests.ts";
import type {
	CreateSceneItemRequest,
	CreateSceneItemResponse,
	DuplicateSceneItemRequest,
	DuplicateSceneItemResponse,
	GetGroupSceneItemListRequest,
	GetGroupSceneItemListResponse,
	GetSceneItemBlendModeRequest,
	GetSceneItemBlendModeResponse,
	GetSceneItemEnabledRequest,
	GetSceneItemEnabledResponse,
	GetSceneItemIdRequest,
	GetSceneItemIdResponse,
	GetSceneItemIndexRequest,
	GetSceneItemIndexResponse,
	GetSceneItemListRequest,
	GetSceneItemListResponse,
	GetSceneItemLockedRequest,
	GetSceneItemLockedResponse,
	GetSceneItemSourceRequest,
	GetSceneItemSourceResponse,
	GetSceneItemTransformRequest,
	GetSceneItemTransformResponse,
	RemoveSceneItemRequest,
	SetSceneItemBlendModeRequest,
	SetSceneItemEnabledRequest,
	SetSceneItemIndexRequest,
	SetSceneItemLockedRequest,
	SetSceneItemTransformRequest,
} from "../requests.ts";
import {
	SceneItemCreated,
	SceneItemEnableStateChanged,
	SceneItemListReindexed,
	SceneItemLockStateChanged,
	SceneItemRemoved,
	SceneItemSelected,
	SceneItemTransformChanged,
} from "../events.ts";
import type {
	SceneItemCreatedPayload,
	SceneItemEnableStateChangedPayload,
	SceneItemListReindexedPayload,
	SceneItemLockStateChangedPayload,
	SceneItemRemovedPayload,
	SceneItemSelectedPayload,
	SceneItemTransformChangedPayload,
} from "../events.ts";

export class ObsSceneItems {
	obs: ObsWs;
	constructor(obs: ObsWs) {
		this.obs = obs;
	}

	/** Creates a new scene item using a source.

Scenes only */
	createSceneItem(
		request: CreateSceneItemRequest,
	): Promise<CreateSceneItemResponse> {
		return this.obs.call(CreateSceneItem, request);
	}

	/** Duplicates a scene item, copying all transform and crop info.

Scenes only */
	duplicateSceneItem(
		request: DuplicateSceneItemRequest,
	): Promise<DuplicateSceneItemResponse> {
		return this.obs.call(DuplicateSceneItem, request);
	}

	/** Basically GetSceneItemList, but for groups.

Using groups at all in OBS is discouraged, as they are very broken under the hood. Please use nested scenes instead.

Groups only */
	getGroupSceneItemList(
		request: GetGroupSceneItemListRequest,
	): Promise<GetGroupSceneItemListResponse> {
		return this.obs.call(GetGroupSceneItemList, request);
	}

	/** Gets the blend mode of a scene item.

Blend modes:

- `OBS_BLEND_NORMAL`
- `OBS_BLEND_ADDITIVE`
- `OBS_BLEND_SUBTRACT`
- `OBS_BLEND_SCREEN`
- `OBS_BLEND_MULTIPLY`
- `OBS_BLEND_LIGHTEN`
- `OBS_BLEND_DARKEN`

Scenes and Groups */
	getSceneItemBlendMode(
		request: GetSceneItemBlendModeRequest,
	): Promise<GetSceneItemBlendModeResponse> {
		return this.obs.call(GetSceneItemBlendMode, request);
	}

	/** Gets the enable state of a scene item.

Scenes and Groups */
	getSceneItemEnabled(
		request: GetSceneItemEnabledRequest,
	): Promise<GetSceneItemEnabledResponse> {
		return this.obs.call(GetSceneItemEnabled, request);
	}

	/** Searches a scene for a source, and returns its id.

Scenes and Groups */
	getSceneItemId(
		request: GetSceneItemIdRequest,
	): Promise<GetSceneItemIdResponse> {
		return this.obs.call(GetSceneItemId, request);
	}

	/** Gets the index position of a scene item in a scene.

An index of 0 is at the bottom of the source list in the UI.

Scenes and Groups */
	getSceneItemIndex(
		request: GetSceneItemIndexRequest,
	): Promise<GetSceneItemIndexResponse> {
		return this.obs.call(GetSceneItemIndex, request);
	}

	/** Gets a list of all scene items in a scene.

Scenes only */
	getSceneItemList(
		request: GetSceneItemListRequest,
	): Promise<GetSceneItemListResponse> {
		return this.obs.call(GetSceneItemList, request);
	}

	/** Gets the lock state of a scene item.

Scenes and Groups */
	getSceneItemLocked(
		request: GetSceneItemLockedRequest,
	): Promise<GetSceneItemLockedResponse> {
		return this.obs.call(GetSceneItemLocked, request);
	}

	/** Gets the source associated with a scene item. */
	getSceneItemSource(
		request: GetSceneItemSourceRequest,
	): Promise<GetSceneItemSourceResponse> {
		return this.obs.call(GetSceneItemSource, request);
	}

	/** Gets the transform and crop info of a scene item.

Scenes and Groups */
	getSceneItemTransform(
		request: GetSceneItemTransformRequest,
	): Promise<GetSceneItemTransformResponse> {
		return this.obs.call(GetSceneItemTransform, request);
	}

	/** Removes a scene item from a scene.

Scenes only */
	removeSceneItem(request: RemoveSceneItemRequest): Promise<void> {
		return this.obs.call(RemoveSceneItem, request);
	}

	/** Sets the blend mode of a scene item.

Scenes and Groups */
	setSceneItemBlendMode(request: SetSceneItemBlendModeRequest): Promise<void> {
		return this.obs.call(SetSceneItemBlendMode, request);
	}

	/** Sets the enable state of a scene item.

Scenes and Groups */
	setSceneItemEnabled(request: SetSceneItemEnabledRequest): Promise<void> {
		return this.obs.call(SetSceneItemEnabled, request);
	}

	/** Sets the index position of a scene item in a scene.

Scenes and Groups */
	setSceneItemIndex(request: SetSceneItemIndexRequest): Promise<void> {
		return this.obs.call(SetSceneItemIndex, request);
	}

	/** Sets the lock state of a scene item.

Scenes and Group */
	setSceneItemLocked(request: SetSceneItemLockedRequest): Promise<void> {
		return this.obs.call(SetSceneItemLocked, request);
	}

	/** Sets the transform and crop info of a scene item. */
	setSceneItemTransform(request: SetSceneItemTransformRequest): Promise<void> {
		return this.obs.call(SetSceneItemTransform, request);
	}

	/** A scene item has been created. */
	onSceneItemCreated(
		callback: (payload: SceneItemCreatedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SceneItemCreated, callback);
	}

	/** A scene item's enable state has changed. */
	onSceneItemEnableStateChanged(
		callback: (payload: SceneItemEnableStateChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SceneItemEnableStateChanged, callback);
	}

	/** A scene's item list has been reindexed. */
	onSceneItemListReindexed(
		callback: (payload: SceneItemListReindexedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SceneItemListReindexed, callback);
	}

	/** A scene item's lock state has changed. */
	onSceneItemLockStateChanged(
		callback: (payload: SceneItemLockStateChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SceneItemLockStateChanged, callback);
	}

	/** A scene item has been removed.

This event is not emitted when the scene the item is in is removed. */
	onSceneItemRemoved(
		callback: (payload: SceneItemRemovedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SceneItemRemoved, callback);
	}

	/** A scene item has been selected in the Ui. */
	onSceneItemSelected(
		callback: (payload: SceneItemSelectedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SceneItemSelected, callback);
	}

	/** The transform/crop of a scene item has changed. */
	onSceneItemTransformChanged(
		callback: (payload: SceneItemTransformChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SceneItemTransformChanged, callback);
	}
}
