// This file is @generated by scripts/wrappers.ts

import type { ObsWs } from "../client.ts";
import {
	CreateScene,
	GetCurrentPreviewScene,
	GetCurrentProgramScene,
	GetGroupList,
	GetSceneList,
	GetSceneSceneTransitionOverride,
	RemoveScene,
	SetCurrentPreviewScene,
	SetCurrentProgramScene,
	SetSceneName,
	SetSceneSceneTransitionOverride,
} from "../requests.ts";
import type {
	CreateSceneRequest,
	CreateSceneResponse,
	GetCurrentPreviewSceneResponse,
	GetCurrentProgramSceneResponse,
	GetGroupListResponse,
	GetSceneListResponse,
	GetSceneSceneTransitionOverrideRequest,
	GetSceneSceneTransitionOverrideResponse,
	RemoveSceneRequest,
	SetCurrentPreviewSceneRequest,
	SetCurrentProgramSceneRequest,
	SetSceneNameRequest,
	SetSceneSceneTransitionOverrideRequest,
} from "../requests.ts";
import {
	CurrentPreviewSceneChanged,
	CurrentProgramSceneChanged,
	SceneCreated,
	SceneListChanged,
	SceneNameChanged,
	SceneRemoved,
} from "../events.ts";
import type {
	CurrentPreviewSceneChangedPayload,
	CurrentProgramSceneChangedPayload,
	SceneCreatedPayload,
	SceneListChangedPayload,
	SceneNameChangedPayload,
	SceneRemovedPayload,
} from "../events.ts";

export class ObsScenes {
	obs: ObsWs;
	constructor(obs: ObsWs) {
		this.obs = obs;
	}

	/** Creates a new scene in OBS. */
	createScene(request: CreateSceneRequest): Promise<CreateSceneResponse> {
		return this.obs.call(CreateScene, request);
	}

	/** Gets the current preview scene.

Only available when studio mode is enabled.

Note: This request is slated to have the `currentPreview`-prefixed fields removed from in an upcoming RPC version. */
	getCurrentPreviewScene(): Promise<GetCurrentPreviewSceneResponse> {
		return this.obs.call(GetCurrentPreviewScene, undefined);
	}

	/** Gets the current program scene.

Note: This request is slated to have the `currentProgram`-prefixed fields removed from in an upcoming RPC version. */
	getCurrentProgramScene(): Promise<GetCurrentProgramSceneResponse> {
		return this.obs.call(GetCurrentProgramScene, undefined);
	}

	/** Gets an array of all groups in OBS.

Groups in OBS are actually scenes, but renamed and modified. In obs-websocket, we treat them as scenes where we can. */
	getGroupList(): Promise<GetGroupListResponse> {
		return this.obs.call(GetGroupList, undefined);
	}

	/** Gets an array of all scenes in OBS. */
	getSceneList(): Promise<GetSceneListResponse> {
		return this.obs.call(GetSceneList, undefined);
	}

	/** Gets the scene transition overridden for a scene.

Note: A transition UUID response field is not currently able to be implemented as of 2024-1-18. */
	getSceneSceneTransitionOverride(
		request: GetSceneSceneTransitionOverrideRequest,
	): Promise<GetSceneSceneTransitionOverrideResponse> {
		return this.obs.call(GetSceneSceneTransitionOverride, request);
	}

	/** Removes a scene from OBS. */
	removeScene(request: RemoveSceneRequest): Promise<void> {
		return this.obs.call(RemoveScene, request);
	}

	/** Sets the current preview scene.

Only available when studio mode is enabled. */
	setCurrentPreviewScene(
		request: SetCurrentPreviewSceneRequest,
	): Promise<void> {
		return this.obs.call(SetCurrentPreviewScene, request);
	}

	/** Sets the current program scene. */
	setCurrentProgramScene(
		request: SetCurrentProgramSceneRequest,
	): Promise<void> {
		return this.obs.call(SetCurrentProgramScene, request);
	}

	/** Sets the name of a scene (rename). */
	setSceneName(request: SetSceneNameRequest): Promise<void> {
		return this.obs.call(SetSceneName, request);
	}

	/** Sets the scene transition overridden for a scene. */
	setSceneSceneTransitionOverride(
		request: SetSceneSceneTransitionOverrideRequest,
	): Promise<void> {
		return this.obs.call(SetSceneSceneTransitionOverride, request);
	}

	/** The current preview scene has changed. */
	onCurrentPreviewSceneChanged(
		callback: (payload: CurrentPreviewSceneChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(CurrentPreviewSceneChanged, callback);
	}

	/** The current program scene has changed. */
	onCurrentProgramSceneChanged(
		callback: (payload: CurrentProgramSceneChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(CurrentProgramSceneChanged, callback);
	}

	/** A new scene has been created. */
	onSceneCreated(
		callback: (payload: SceneCreatedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SceneCreated, callback);
	}

	/** The list of scenes has changed.

TODO: Make OBS fire this event when scenes are reordered. */
	onSceneListChanged(
		callback: (payload: SceneListChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SceneListChanged, callback);
	}

	/** The name of a scene has changed. */
	onSceneNameChanged(
		callback: (payload: SceneNameChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SceneNameChanged, callback);
	}

	/** A scene has been removed. */
	onSceneRemoved(
		callback: (payload: SceneRemovedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SceneRemoved, callback);
	}
}
