// This file is @generated by scripts/wrappers.ts

import type { ObsWs } from "../client.ts";
import {
	GetSourceActive,
	GetSourceScreenshot,
	SaveSourceScreenshot,
} from "../requests.ts";
import type {
	GetSourceActiveRequest,
	GetSourceActiveResponse,
	GetSourceScreenshotRequest,
	GetSourceScreenshotResponse,
	SaveSourceScreenshotRequest,
} from "../requests.ts";
import {} from "../events.ts";
import type {} from "../events.ts";

export class ObsSources {
	obs: ObsWs;
	constructor(obs: ObsWs) {
		this.obs = obs;
	}

	/** Gets the active and show state of a source.

**Compatible with inputs and scenes.** */
	getSourceActive(
		request: GetSourceActiveRequest,
	): Promise<GetSourceActiveResponse> {
		return this.obs.call(GetSourceActive, request);
	}

	/** Gets a Base64-encoded screenshot of a source.

The `imageWidth` and `imageHeight` parameters are treated as "scale to inner", meaning the smallest ratio will be used and the aspect ratio of the original resolution is kept.
If `imageWidth` and `imageHeight` are not specified, the compressed image will use the full resolution of the source.

**Compatible with inputs and scenes.** */
	getSourceScreenshot(
		request: GetSourceScreenshotRequest,
	): Promise<GetSourceScreenshotResponse> {
		return this.obs.call(GetSourceScreenshot, request);
	}

	/** Saves a screenshot of a source to the filesystem.

The `imageWidth` and `imageHeight` parameters are treated as "scale to inner", meaning the smallest ratio will be used and the aspect ratio of the original resolution is kept.
If `imageWidth` and `imageHeight` are not specified, the compressed image will use the full resolution of the source.

**Compatible with inputs and scenes.** */
	saveSourceScreenshot(request: SaveSourceScreenshotRequest): Promise<void> {
		return this.obs.call(SaveSourceScreenshot, request);
	}
}
