// This file is @generated by scripts/wrappers.ts

import type { ObsWs } from "../client.ts";
import {
	GetStreamStatus,
	SendStreamCaption,
	StartStream,
	StopStream,
	ToggleStream,
} from "../requests.ts";
import type {
	GetStreamStatusResponse,
	SendStreamCaptionRequest,
	ToggleStreamResponse,
} from "../requests.ts";
import {} from "../events.ts";
import type {} from "../events.ts";

export class ObsStream {
	obs: ObsWs;
	constructor(obs: ObsWs) {
		this.obs = obs;
	}

	/** Gets the status of the stream output. */
	getStreamStatus(): Promise<GetStreamStatusResponse> {
		return this.obs.call(GetStreamStatus, undefined);
	}

	/** Sends CEA-608 caption text over the stream output. */
	sendStreamCaption(request: SendStreamCaptionRequest): Promise<void> {
		return this.obs.call(SendStreamCaption, request);
	}

	/** Starts the stream output. */
	startStream(): Promise<void> {
		return this.obs.call(StartStream, undefined);
	}

	/** Stops the stream output. */
	stopStream(): Promise<void> {
		return this.obs.call(StopStream, undefined);
	}

	/** Toggles the status of the stream output. */
	toggleStream(): Promise<ToggleStreamResponse> {
		return this.obs.call(ToggleStream, undefined);
	}
}
