// This file is @generated by scripts/wrappers.ts

import type { ObsWs } from "../client.ts";
import {
	GetCurrentSceneTransition,
	GetCurrentSceneTransitionCursor,
	GetSceneTransitionList,
	GetTransitionKindList,
	SetCurrentSceneTransition,
	SetCurrentSceneTransitionDuration,
	SetCurrentSceneTransitionSettings,
	SetTBarPosition,
	TriggerStudioModeTransition,
} from "../requests.ts";
import type {
	GetCurrentSceneTransitionCursorResponse,
	GetCurrentSceneTransitionResponse,
	GetSceneTransitionListResponse,
	GetTransitionKindListResponse,
	SetCurrentSceneTransitionDurationRequest,
	SetCurrentSceneTransitionRequest,
	SetCurrentSceneTransitionSettingsRequest,
	SetTBarPositionRequest,
} from "../requests.ts";
import {
	CurrentSceneTransitionChanged,
	CurrentSceneTransitionDurationChanged,
	SceneTransitionEnded,
	SceneTransitionStarted,
	SceneTransitionVideoEnded,
} from "../events.ts";
import type {
	CurrentSceneTransitionChangedPayload,
	CurrentSceneTransitionDurationChangedPayload,
	SceneTransitionEndedPayload,
	SceneTransitionStartedPayload,
	SceneTransitionVideoEndedPayload,
} from "../events.ts";

export class ObsTransitions {
	obs: ObsWs;
	constructor(obs: ObsWs) {
		this.obs = obs;
	}

	/** Gets information about the current scene transition. */
	getCurrentSceneTransition(): Promise<GetCurrentSceneTransitionResponse> {
		return this.obs.call(GetCurrentSceneTransition, undefined);
	}

	/** Gets the cursor position of the current scene transition.

Note: `transitionCursor` will return 1.0 when the transition is inactive. */
	getCurrentSceneTransitionCursor(): Promise<
		GetCurrentSceneTransitionCursorResponse
	> {
		return this.obs.call(GetCurrentSceneTransitionCursor, undefined);
	}

	/** Gets an array of all scene transitions in OBS. */
	getSceneTransitionList(): Promise<GetSceneTransitionListResponse> {
		return this.obs.call(GetSceneTransitionList, undefined);
	}

	/** Gets an array of all available transition kinds.

Similar to `GetInputKindList` */
	getTransitionKindList(): Promise<GetTransitionKindListResponse> {
		return this.obs.call(GetTransitionKindList, undefined);
	}

	/** Sets the current scene transition.

Small note: While the namespace of scene transitions is generally unique, that uniqueness is not a guarantee as it is with other resources like inputs. */
	setCurrentSceneTransition(
		request: SetCurrentSceneTransitionRequest,
	): Promise<void> {
		return this.obs.call(SetCurrentSceneTransition, request);
	}

	/** Sets the duration of the current scene transition, if it is not fixed. */
	setCurrentSceneTransitionDuration(
		request: SetCurrentSceneTransitionDurationRequest,
	): Promise<void> {
		return this.obs.call(SetCurrentSceneTransitionDuration, request);
	}

	/** Sets the settings of the current scene transition. */
	setCurrentSceneTransitionSettings(
		request: SetCurrentSceneTransitionSettingsRequest,
	): Promise<void> {
		return this.obs.call(SetCurrentSceneTransitionSettings, request);
	}

	/** Sets the position of the TBar.

**Very important note**: This will be deprecated and replaced in a future version of obs-websocket. */
	setTBarPosition(request: SetTBarPositionRequest): Promise<void> {
		return this.obs.call(SetTBarPosition, request);
	}

	/** Triggers the current scene transition. Same functionality as the `Transition` button in studio mode. */
	triggerStudioModeTransition(): Promise<void> {
		return this.obs.call(TriggerStudioModeTransition, undefined);
	}

	/** The current scene transition has changed. */
	onCurrentSceneTransitionChanged(
		callback: (payload: CurrentSceneTransitionChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(CurrentSceneTransitionChanged, callback);
	}

	/** The current scene transition duration has changed. */
	onCurrentSceneTransitionDurationChanged(
		callback: (payload: CurrentSceneTransitionDurationChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(CurrentSceneTransitionDurationChanged, callback);
	}

	/** A scene transition has completed fully.

Note: Does not appear to trigger when the transition is interrupted by the user. */
	onSceneTransitionEnded(
		callback: (payload: SceneTransitionEndedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SceneTransitionEnded, callback);
	}

	/** A scene transition has started. */
	onSceneTransitionStarted(
		callback: (payload: SceneTransitionStartedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SceneTransitionStarted, callback);
	}

	/** A scene transition's video has completed fully.

Useful for stinger transitions to tell when the video *actually* ends.
`SceneTransitionEnded` only signifies the cut point, not the completion of transition playback.

Note: Appears to be called by every transition, regardless of relevance. */
	onSceneTransitionVideoEnded(
		callback: (payload: SceneTransitionVideoEndedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(SceneTransitionVideoEnded, callback);
	}
}
