// This file is @generated by scripts/wrappers.ts

import type { ObsWs } from "../client.ts";
import {
	GetMonitorList,
	GetStudioModeEnabled,
	OpenInputFiltersDialog,
	OpenInputInteractDialog,
	OpenInputPropertiesDialog,
	OpenSourceProjector,
	OpenVideoMixProjector,
	SetStudioModeEnabled,
} from "../requests.ts";
import type {
	GetMonitorListResponse,
	GetStudioModeEnabledResponse,
	OpenInputFiltersDialogRequest,
	OpenInputInteractDialogRequest,
	OpenInputPropertiesDialogRequest,
	OpenSourceProjectorRequest,
	OpenVideoMixProjectorRequest,
	SetStudioModeEnabledRequest,
} from "../requests.ts";
import { ScreenshotSaved, StudioModeStateChanged } from "../events.ts";
import type {
	ScreenshotSavedPayload,
	StudioModeStateChangedPayload,
} from "../events.ts";

export class ObsUi {
	obs: ObsWs;
	constructor(obs: ObsWs) {
		this.obs = obs;
	}

	/** Gets a list of connected monitors and information about them. */
	getMonitorList(): Promise<GetMonitorListResponse> {
		return this.obs.call(GetMonitorList, undefined);
	}

	/** Gets whether studio is enabled. */
	getStudioModeEnabled(): Promise<GetStudioModeEnabledResponse> {
		return this.obs.call(GetStudioModeEnabled, undefined);
	}

	/** Opens the filters dialog of an input. */
	openInputFiltersDialog(
		request: OpenInputFiltersDialogRequest,
	): Promise<void> {
		return this.obs.call(OpenInputFiltersDialog, request);
	}

	/** Opens the interact dialog of an input. */
	openInputInteractDialog(
		request: OpenInputInteractDialogRequest,
	): Promise<void> {
		return this.obs.call(OpenInputInteractDialog, request);
	}

	/** Opens the properties dialog of an input. */
	openInputPropertiesDialog(
		request: OpenInputPropertiesDialogRequest,
	): Promise<void> {
		return this.obs.call(OpenInputPropertiesDialog, request);
	}

	/** Opens a projector for a source.

Note: This request serves to provide feature parity with 4.x. It is very likely to be changed/deprecated in a future release. */
	openSourceProjector(request: OpenSourceProjectorRequest): Promise<void> {
		return this.obs.call(OpenSourceProjector, request);
	}

	/** Opens a projector for a specific output video mix.

Mix types:

- `OBS_WEBSOCKET_VIDEO_MIX_TYPE_PREVIEW`
- `OBS_WEBSOCKET_VIDEO_MIX_TYPE_PROGRAM`
- `OBS_WEBSOCKET_VIDEO_MIX_TYPE_MULTIVIEW`

Note: This request serves to provide feature parity with 4.x. It is very likely to be changed/deprecated in a future release. */
	openVideoMixProjector(request: OpenVideoMixProjectorRequest): Promise<void> {
		return this.obs.call(OpenVideoMixProjector, request);
	}

	/** Enables or disables studio mode */
	setStudioModeEnabled(request: SetStudioModeEnabledRequest): Promise<void> {
		return this.obs.call(SetStudioModeEnabled, request);
	}

	/** A screenshot has been saved.

Note: Triggered for the screenshot feature available in `Settings -> Hotkeys -> Screenshot Output` ONLY.
Applications using `Get/SaveSourceScreenshot` should implement a `CustomEvent` if this kind of inter-client
communication is desired. */
	onScreenshotSaved(
		callback: (payload: ScreenshotSavedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(ScreenshotSaved, callback);
	}

	/** Studio mode has been enabled or disabled. */
	onStudioModeStateChanged(
		callback: (payload: StudioModeStateChangedPayload) => void,
	): Promise<void> {
		return this.obs.subscribe(StudioModeStateChanged, callback);
	}
}
