// This file is @generated by scripts/events.ts

export class ObsEvent<Payload> {
	type: string;
	mask: number;
	constructor(type: string, mask: number) {
		this.type = type;
		this.mask = mask;
	}
}

/** Payload for {@link CurrentPreviewSceneChanged} */
export type CurrentPreviewSceneChangedPayload = {
	/** Name of the scene that was switched to */
	sceneName: string;
	/** UUID of the scene that was switched to */
	sceneUuid: string;
};

/** The current preview scene has changed. */
export const CurrentPreviewSceneChanged: ObsEvent<
	CurrentPreviewSceneChangedPayload
> = new ObsEvent<CurrentPreviewSceneChangedPayload>(
	"CurrentPreviewSceneChanged",
	1 << 2,
);

/** Payload for {@link CurrentProfileChanged} */
export type CurrentProfileChangedPayload = {
	/** Name of the new profile */
	profileName: string;
};

/** The current profile has changed. */
export const CurrentProfileChanged: ObsEvent<CurrentProfileChangedPayload> =
	new ObsEvent<CurrentProfileChangedPayload>("CurrentProfileChanged", 1 << 1);

/** Payload for {@link CurrentProfileChanging} */
export type CurrentProfileChangingPayload = {
	/** Name of the current profile */
	profileName: string;
};

/** The current profile has begun changing. */
export const CurrentProfileChanging: ObsEvent<CurrentProfileChangingPayload> =
	new ObsEvent<CurrentProfileChangingPayload>("CurrentProfileChanging", 1 << 1);

/** Payload for {@link CurrentProgramSceneChanged} */
export type CurrentProgramSceneChangedPayload = {
	/** Name of the scene that was switched to */
	sceneName: string;
	/** UUID of the scene that was switched to */
	sceneUuid: string;
};

/** The current program scene has changed. */
export const CurrentProgramSceneChanged: ObsEvent<
	CurrentProgramSceneChangedPayload
> = new ObsEvent<CurrentProgramSceneChangedPayload>(
	"CurrentProgramSceneChanged",
	1 << 2,
);

/** Payload for {@link CurrentSceneCollectionChanged} */
export type CurrentSceneCollectionChangedPayload = {
	/** Name of the new scene collection */
	sceneCollectionName: string;
};

/** The current scene collection has changed.

Note: If polling has been paused during `CurrentSceneCollectionChanging`, this is the que to restart polling. */
export const CurrentSceneCollectionChanged: ObsEvent<
	CurrentSceneCollectionChangedPayload
> = new ObsEvent<CurrentSceneCollectionChangedPayload>(
	"CurrentSceneCollectionChanged",
	1 << 1,
);

/** Payload for {@link CurrentSceneCollectionChanging} */
export type CurrentSceneCollectionChangingPayload = {
	/** Name of the current scene collection */
	sceneCollectionName: string;
};

/** The current scene collection has begun changing.

Note: We recommend using this event to trigger a pause of all polling requests, as performing any requests during a
scene collection change is considered undefined behavior and can cause crashes! */
export const CurrentSceneCollectionChanging: ObsEvent<
	CurrentSceneCollectionChangingPayload
> = new ObsEvent<CurrentSceneCollectionChangingPayload>(
	"CurrentSceneCollectionChanging",
	1 << 1,
);

/** Payload for {@link CurrentSceneTransitionChanged} */
export type CurrentSceneTransitionChangedPayload = {
	/** Name of the new transition */
	transitionName: string;
	/** UUID of the new transition */
	transitionUuid: string;
};

/** The current scene transition has changed. */
export const CurrentSceneTransitionChanged: ObsEvent<
	CurrentSceneTransitionChangedPayload
> = new ObsEvent<CurrentSceneTransitionChangedPayload>(
	"CurrentSceneTransitionChanged",
	1 << 4,
);

/** Payload for {@link CurrentSceneTransitionDurationChanged} */
export type CurrentSceneTransitionDurationChangedPayload = {
	/** Transition duration in milliseconds */
	transitionDuration: number;
};

/** The current scene transition duration has changed. */
export const CurrentSceneTransitionDurationChanged: ObsEvent<
	CurrentSceneTransitionDurationChangedPayload
> = new ObsEvent<CurrentSceneTransitionDurationChangedPayload>(
	"CurrentSceneTransitionDurationChanged",
	1 << 4,
);

/** Payload for {@link CustomEvent} */
export type CustomEventPayload = {
	/** Custom event data */
	eventData: object;
};

/** Custom event emitted by `BroadcastCustomEvent`. */
export const CustomEvent: ObsEvent<CustomEventPayload> = new ObsEvent<
	CustomEventPayload
>("CustomEvent", 1 << 0);

/** OBS has begun the shutdown process. */
export const ExitStarted: ObsEvent<Record<PropertyKey, never>> = new ObsEvent<
	Record<PropertyKey, never>
>("ExitStarted", 1 << 0);

/** Payload for {@link InputActiveStateChanged} */
export type InputActiveStateChangedPayload = {
	/** Name of the input */
	inputName: string;
	/** UUID of the input */
	inputUuid: string;
	/** Whether the input is active */
	videoActive: boolean;
};

/** An input's active state has changed.

When an input is active, it means it's being shown by the program feed. */
export const InputActiveStateChanged: ObsEvent<InputActiveStateChangedPayload> =
	new ObsEvent<InputActiveStateChangedPayload>(
		"InputActiveStateChanged",
		1 << 17,
	);

/** Payload for {@link InputAudioBalanceChanged} */
export type InputAudioBalanceChangedPayload = {
	/** Name of the input */
	inputName: string;
	/** UUID of the input */
	inputUuid: string;
	/** New audio balance value of the input */
	inputAudioBalance: number;
};

/** The audio balance value of an input has changed. */
export const InputAudioBalanceChanged: ObsEvent<
	InputAudioBalanceChangedPayload
> = new ObsEvent<InputAudioBalanceChangedPayload>(
	"InputAudioBalanceChanged",
	1 << 3,
);

/** Payload for {@link InputAudioMonitorTypeChanged} */
export type InputAudioMonitorTypeChangedPayload = {
	/** Name of the input */
	inputName: string;
	/** UUID of the input */
	inputUuid: string;
	/** New monitor type of the input */
	monitorType: string;
};

/** The monitor type of an input has changed.

Available types are:

- `OBS_MONITORING_TYPE_NONE`
- `OBS_MONITORING_TYPE_MONITOR_ONLY`
- `OBS_MONITORING_TYPE_MONITOR_AND_OUTPUT` */
export const InputAudioMonitorTypeChanged: ObsEvent<
	InputAudioMonitorTypeChangedPayload
> = new ObsEvent<InputAudioMonitorTypeChangedPayload>(
	"InputAudioMonitorTypeChanged",
	1 << 3,
);

/** Payload for {@link InputAudioSyncOffsetChanged} */
export type InputAudioSyncOffsetChangedPayload = {
	/** Name of the input */
	inputName: string;
	/** UUID of the input */
	inputUuid: string;
	/** New sync offset in milliseconds */
	inputAudioSyncOffset: number;
};

/** The sync offset of an input has changed. */
export const InputAudioSyncOffsetChanged: ObsEvent<
	InputAudioSyncOffsetChangedPayload
> = new ObsEvent<InputAudioSyncOffsetChangedPayload>(
	"InputAudioSyncOffsetChanged",
	1 << 3,
);

/** Payload for {@link InputAudioTracksChanged} */
export type InputAudioTracksChangedPayload = {
	/** Name of the input */
	inputName: string;
	/** UUID of the input */
	inputUuid: string;
	/** Object of audio tracks along with their associated enable states */
	inputAudioTracks: object;
};

/** The audio tracks of an input have changed. */
export const InputAudioTracksChanged: ObsEvent<InputAudioTracksChangedPayload> =
	new ObsEvent<InputAudioTracksChangedPayload>(
		"InputAudioTracksChanged",
		1 << 3,
	);

/** Payload for {@link InputCreated} */
export type InputCreatedPayload = {
	/** Name of the input */
	inputName: string;
	/** UUID of the input */
	inputUuid: string;
	/** The kind of the input */
	inputKind: string;
	/** The unversioned kind of input (aka no `_v2` stuff) */
	unversionedInputKind: string;
	/** Bitflag value for the caps that an input supports. See obs_source_info.output_flags in the libobs docs */
	inputKindCaps: number;
	/** The settings configured to the input when it was created */
	inputSettings: object;
	/** The default settings for the input */
	defaultInputSettings: object;
};

/** An input has been created. */
export const InputCreated: ObsEvent<InputCreatedPayload> = new ObsEvent<
	InputCreatedPayload
>("InputCreated", 1 << 3);

/** Payload for {@link InputMuteStateChanged} */
export type InputMuteStateChangedPayload = {
	/** Name of the input */
	inputName: string;
	/** UUID of the input */
	inputUuid: string;
	/** Whether the input is muted */
	inputMuted: boolean;
};

/** An input's mute state has changed. */
export const InputMuteStateChanged: ObsEvent<InputMuteStateChangedPayload> =
	new ObsEvent<InputMuteStateChangedPayload>("InputMuteStateChanged", 1 << 3);

/** Payload for {@link InputNameChanged} */
export type InputNameChangedPayload = {
	/** UUID of the input */
	inputUuid: string;
	/** Old name of the input */
	oldInputName: string;
	/** New name of the input */
	inputName: string;
};

/** The name of an input has changed. */
export const InputNameChanged: ObsEvent<InputNameChangedPayload> = new ObsEvent<
	InputNameChangedPayload
>("InputNameChanged", 1 << 3);

/** Payload for {@link InputRemoved} */
export type InputRemovedPayload = {
	/** Name of the input */
	inputName: string;
	/** UUID of the input */
	inputUuid: string;
};

/** An input has been removed. */
export const InputRemoved: ObsEvent<InputRemovedPayload> = new ObsEvent<
	InputRemovedPayload
>("InputRemoved", 1 << 3);

/** Payload for {@link InputSettingsChanged} */
export type InputSettingsChangedPayload = {
	/** Name of the input */
	inputName: string;
	/** UUID of the input */
	inputUuid: string;
	/** New settings object of the input */
	inputSettings: object;
};

/** An input's settings have changed (been updated).

Note: On some inputs, changing values in the properties dialog will cause an immediate update. Pressing the "Cancel" button will revert the settings, resulting in another event being fired. */
export const InputSettingsChanged: ObsEvent<InputSettingsChangedPayload> =
	new ObsEvent<InputSettingsChangedPayload>("InputSettingsChanged", 1 << 3);

/** Payload for {@link InputShowStateChanged} */
export type InputShowStateChangedPayload = {
	/** Name of the input */
	inputName: string;
	/** UUID of the input */
	inputUuid: string;
	/** Whether the input is showing */
	videoShowing: boolean;
};

/** An input's show state has changed.

When an input is showing, it means it's being shown by the preview or a dialog. */
export const InputShowStateChanged: ObsEvent<InputShowStateChangedPayload> =
	new ObsEvent<InputShowStateChangedPayload>("InputShowStateChanged", 1 << 18);

/** Payload for {@link InputVolumeChanged} */
export type InputVolumeChangedPayload = {
	/** Name of the input */
	inputName: string;
	/** UUID of the input */
	inputUuid: string;
	/** New volume level multiplier */
	inputVolumeMul: number;
	/** New volume level in dB */
	inputVolumeDb: number;
};

/** An input's volume level has changed. */
export const InputVolumeChanged: ObsEvent<InputVolumeChangedPayload> =
	new ObsEvent<InputVolumeChangedPayload>("InputVolumeChanged", 1 << 3);

/** Payload for {@link InputVolumeMeters} */
export type InputVolumeMetersPayload = {
	/** Array of active inputs with their associated volume levels */
	inputs: object[];
};

/** A high-volume event providing volume levels of all active inputs every 50 milliseconds. */
export const InputVolumeMeters: ObsEvent<InputVolumeMetersPayload> =
	new ObsEvent<InputVolumeMetersPayload>("InputVolumeMeters", 1 << 16);

/** Payload for {@link MediaInputActionTriggered} */
export type MediaInputActionTriggeredPayload = {
	/** Name of the input */
	inputName: string;
	/** UUID of the input */
	inputUuid: string;
	/** Action performed on the input. See `ObsMediaInputAction` enum */
	mediaAction: string;
};

/** An action has been performed on an input. */
export const MediaInputActionTriggered: ObsEvent<
	MediaInputActionTriggeredPayload
> = new ObsEvent<MediaInputActionTriggeredPayload>(
	"MediaInputActionTriggered",
	1 << 8,
);

/** Payload for {@link MediaInputPlaybackEnded} */
export type MediaInputPlaybackEndedPayload = {
	/** Name of the input */
	inputName: string;
	/** UUID of the input */
	inputUuid: string;
};

/** A media input has finished playing. */
export const MediaInputPlaybackEnded: ObsEvent<MediaInputPlaybackEndedPayload> =
	new ObsEvent<MediaInputPlaybackEndedPayload>(
		"MediaInputPlaybackEnded",
		1 << 8,
	);

/** Payload for {@link MediaInputPlaybackStarted} */
export type MediaInputPlaybackStartedPayload = {
	/** Name of the input */
	inputName: string;
	/** UUID of the input */
	inputUuid: string;
};

/** A media input has started playing. */
export const MediaInputPlaybackStarted: ObsEvent<
	MediaInputPlaybackStartedPayload
> = new ObsEvent<MediaInputPlaybackStartedPayload>(
	"MediaInputPlaybackStarted",
	1 << 8,
);

/** Payload for {@link ProfileListChanged} */
export type ProfileListChangedPayload = {
	/** Updated list of profiles */
	profiles: string[];
};

/** The profile list has changed. */
export const ProfileListChanged: ObsEvent<ProfileListChangedPayload> =
	new ObsEvent<ProfileListChangedPayload>("ProfileListChanged", 1 << 1);

/** Payload for {@link RecordFileChanged} */
export type RecordFileChangedPayload = {
	/** File name that the output has begun writing to */
	newOutputPath: string;
};

/** The record output has started writing to a new file. For example, when a file split happens. */
export const RecordFileChanged: ObsEvent<RecordFileChangedPayload> =
	new ObsEvent<RecordFileChangedPayload>("RecordFileChanged", 1 << 6);

/** Payload for {@link RecordStateChanged} */
export type RecordStateChangedPayload = {
	/** Whether the output is active */
	outputActive: boolean;
	/** The specific state of the output */
	outputState: string;
	/** File name for the saved recording, if record stopped. `null` otherwise */
	outputPath: string;
};

/** The state of the record output has changed. */
export const RecordStateChanged: ObsEvent<RecordStateChangedPayload> =
	new ObsEvent<RecordStateChangedPayload>("RecordStateChanged", 1 << 6);

/** Payload for {@link ReplayBufferSaved} */
export type ReplayBufferSavedPayload = {
	/** Path of the saved replay file */
	savedReplayPath: string;
};

/** The replay buffer has been saved. */
export const ReplayBufferSaved: ObsEvent<ReplayBufferSavedPayload> =
	new ObsEvent<ReplayBufferSavedPayload>("ReplayBufferSaved", 1 << 6);

/** Payload for {@link ReplayBufferStateChanged} */
export type ReplayBufferStateChangedPayload = {
	/** Whether the output is active */
	outputActive: boolean;
	/** The specific state of the output */
	outputState: string;
};

/** The state of the replay buffer output has changed. */
export const ReplayBufferStateChanged: ObsEvent<
	ReplayBufferStateChangedPayload
> = new ObsEvent<ReplayBufferStateChangedPayload>(
	"ReplayBufferStateChanged",
	1 << 6,
);

/** Payload for {@link SceneCollectionListChanged} */
export type SceneCollectionListChangedPayload = {
	/** Updated list of scene collections */
	sceneCollections: string[];
};

/** The scene collection list has changed. */
export const SceneCollectionListChanged: ObsEvent<
	SceneCollectionListChangedPayload
> = new ObsEvent<SceneCollectionListChangedPayload>(
	"SceneCollectionListChanged",
	1 << 1,
);

/** Payload for {@link SceneCreated} */
export type SceneCreatedPayload = {
	/** Name of the new scene */
	sceneName: string;
	/** UUID of the new scene */
	sceneUuid: string;
	/** Whether the new scene is a group */
	isGroup: boolean;
};

/** A new scene has been created. */
export const SceneCreated: ObsEvent<SceneCreatedPayload> = new ObsEvent<
	SceneCreatedPayload
>("SceneCreated", 1 << 2);

/** Payload for {@link SceneItemCreated} */
export type SceneItemCreatedPayload = {
	/** Name of the scene the item was added to */
	sceneName: string;
	/** UUID of the scene the item was added to */
	sceneUuid: string;
	/** Name of the underlying source (input/scene) */
	sourceName: string;
	/** UUID of the underlying source (input/scene) */
	sourceUuid: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
	/** Index position of the item */
	sceneItemIndex: number;
};

/** A scene item has been created. */
export const SceneItemCreated: ObsEvent<SceneItemCreatedPayload> = new ObsEvent<
	SceneItemCreatedPayload
>("SceneItemCreated", 1 << 7);

/** Payload for {@link SceneItemEnableStateChanged} */
export type SceneItemEnableStateChangedPayload = {
	/** Name of the scene the item is in */
	sceneName: string;
	/** UUID of the scene the item is in */
	sceneUuid: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
	/** Whether the scene item is enabled (visible) */
	sceneItemEnabled: boolean;
};

/** A scene item's enable state has changed. */
export const SceneItemEnableStateChanged: ObsEvent<
	SceneItemEnableStateChangedPayload
> = new ObsEvent<SceneItemEnableStateChangedPayload>(
	"SceneItemEnableStateChanged",
	1 << 7,
);

/** Payload for {@link SceneItemListReindexed} */
export type SceneItemListReindexedPayload = {
	/** Name of the scene */
	sceneName: string;
	/** UUID of the scene */
	sceneUuid: string;
	/** Array of scene item objects */
	sceneItems: {
		sceneItemId: number;
		sceneItemInedx: number;
	};
};

/** A scene's item list has been reindexed. */
export const SceneItemListReindexed: ObsEvent<SceneItemListReindexedPayload> =
	new ObsEvent<SceneItemListReindexedPayload>("SceneItemListReindexed", 1 << 7);

/** Payload for {@link SceneItemLockStateChanged} */
export type SceneItemLockStateChangedPayload = {
	/** Name of the scene the item is in */
	sceneName: string;
	/** UUID of the scene the item is in */
	sceneUuid: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
	/** Whether the scene item is locked */
	sceneItemLocked: boolean;
};

/** A scene item's lock state has changed. */
export const SceneItemLockStateChanged: ObsEvent<
	SceneItemLockStateChangedPayload
> = new ObsEvent<SceneItemLockStateChangedPayload>(
	"SceneItemLockStateChanged",
	1 << 7,
);

/** Payload for {@link SceneItemRemoved} */
export type SceneItemRemovedPayload = {
	/** Name of the scene the item was removed from */
	sceneName: string;
	/** UUID of the scene the item was removed from */
	sceneUuid: string;
	/** Name of the underlying source (input/scene) */
	sourceName: string;
	/** UUID of the underlying source (input/scene) */
	sourceUuid: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
};

/** A scene item has been removed.

This event is not emitted when the scene the item is in is removed. */
export const SceneItemRemoved: ObsEvent<SceneItemRemovedPayload> = new ObsEvent<
	SceneItemRemovedPayload
>("SceneItemRemoved", 1 << 7);

/** Payload for {@link SceneItemSelected} */
export type SceneItemSelectedPayload = {
	/** Name of the scene the item is in */
	sceneName: string;
	/** UUID of the scene the item is in */
	sceneUuid: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
};

/** A scene item has been selected in the Ui. */
export const SceneItemSelected: ObsEvent<SceneItemSelectedPayload> =
	new ObsEvent<SceneItemSelectedPayload>("SceneItemSelected", 1 << 7);

/** Payload for {@link SceneItemTransformChanged} */
export type SceneItemTransformChangedPayload = {
	/** The name of the scene the item is in */
	sceneName: string;
	/** The UUID of the scene the item is in */
	sceneUuid: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
	/** New transform/crop info of the scene item */
	sceneItemTransform: {
		sourceWidth: number;
		sourceHeight: number;
		positionX: number;
		positionY: number;
		rotation: number;
		scaleX: number;
		scaleY: number;
		width: number;
		height: number;
		alignment: number;
		boundsType: number;
		boundsAlignment: number;
		boundsWidth: number;
		boundsHeight: number;
		cropLeft: number;
		cropRight: number;
		cropTop: number;
		cropBottom: number;
		cropToBounds: boolean;
	};
};

/** The transform/crop of a scene item has changed. */
export const SceneItemTransformChanged: ObsEvent<
	SceneItemTransformChangedPayload
> = new ObsEvent<SceneItemTransformChangedPayload>(
	"SceneItemTransformChanged",
	1 << 19,
);

/** Payload for {@link SceneListChanged} */
export type SceneListChangedPayload = {
	/** Updated array of scenes */
	scenes: {
		sceneName: string;
		sceneUuid: string;
		sceneIndex: number;
	}[];
};

/** The list of scenes has changed.

TODO: Make OBS fire this event when scenes are reordered. */
export const SceneListChanged: ObsEvent<SceneListChangedPayload> = new ObsEvent<
	SceneListChangedPayload
>("SceneListChanged", 1 << 2);

/** Payload for {@link SceneNameChanged} */
export type SceneNameChangedPayload = {
	/** UUID of the scene */
	sceneUuid: string;
	/** Old name of the scene */
	oldSceneName: string;
	/** New name of the scene */
	sceneName: string;
};

/** The name of a scene has changed. */
export const SceneNameChanged: ObsEvent<SceneNameChangedPayload> = new ObsEvent<
	SceneNameChangedPayload
>("SceneNameChanged", 1 << 2);

/** Payload for {@link SceneRemoved} */
export type SceneRemovedPayload = {
	/** Name of the removed scene */
	sceneName: string;
	/** UUID of the removed scene */
	sceneUuid: string;
	/** Whether the scene was a group */
	isGroup: boolean;
};

/** A scene has been removed. */
export const SceneRemoved: ObsEvent<SceneRemovedPayload> = new ObsEvent<
	SceneRemovedPayload
>("SceneRemoved", 1 << 2);

/** Payload for {@link SceneTransitionEnded} */
export type SceneTransitionEndedPayload = {
	/** Scene transition name */
	transitionName: string;
	/** Scene transition UUID */
	transitionUuid: string;
};

/** A scene transition has completed fully.

Note: Does not appear to trigger when the transition is interrupted by the user. */
export const SceneTransitionEnded: ObsEvent<SceneTransitionEndedPayload> =
	new ObsEvent<SceneTransitionEndedPayload>("SceneTransitionEnded", 1 << 4);

/** Payload for {@link SceneTransitionStarted} */
export type SceneTransitionStartedPayload = {
	/** Scene transition name */
	transitionName: string;
	/** Scene transition UUID */
	transitionUuid: string;
};

/** A scene transition has started. */
export const SceneTransitionStarted: ObsEvent<SceneTransitionStartedPayload> =
	new ObsEvent<SceneTransitionStartedPayload>("SceneTransitionStarted", 1 << 4);

/** Payload for {@link SceneTransitionVideoEnded} */
export type SceneTransitionVideoEndedPayload = {
	/** Scene transition name */
	transitionName: string;
	/** Scene transition UUID */
	transitionUuid: string;
};

/** A scene transition's video has completed fully.

Useful for stinger transitions to tell when the video *actually* ends.
`SceneTransitionEnded` only signifies the cut point, not the completion of transition playback.

Note: Appears to be called by every transition, regardless of relevance. */
export const SceneTransitionVideoEnded: ObsEvent<
	SceneTransitionVideoEndedPayload
> = new ObsEvent<SceneTransitionVideoEndedPayload>(
	"SceneTransitionVideoEnded",
	1 << 4,
);

/** Payload for {@link ScreenshotSaved} */
export type ScreenshotSavedPayload = {
	/** Path of the saved image file */
	savedScreenshotPath: string;
};

/** A screenshot has been saved.

Note: Triggered for the screenshot feature available in `Settings -> Hotkeys -> Screenshot Output` ONLY.
Applications using `Get/SaveSourceScreenshot` should implement a `CustomEvent` if this kind of inter-client
communication is desired. */
export const ScreenshotSaved: ObsEvent<ScreenshotSavedPayload> = new ObsEvent<
	ScreenshotSavedPayload
>("ScreenshotSaved", 1 << 10);

/** Payload for {@link SourceFilterCreated} */
export type SourceFilterCreatedPayload = {
	/** Name of the source the filter was added to */
	sourceName: string;
	/** Name of the filter */
	filterName: string;
	/** The kind of the filter */
	filterKind: string;
	/** Index position of the filter */
	filterIndex: number;
	/** The settings configured to the filter when it was created */
	filterSettings: object;
	/** The default settings for the filter */
	defaultFilterSettings: object;
};

/** A filter has been added to a source. */
export const SourceFilterCreated: ObsEvent<SourceFilterCreatedPayload> =
	new ObsEvent<SourceFilterCreatedPayload>("SourceFilterCreated", 1 << 5);

/** Payload for {@link SourceFilterEnableStateChanged} */
export type SourceFilterEnableStateChangedPayload = {
	/** Name of the source the filter is on */
	sourceName: string;
	/** Name of the filter */
	filterName: string;
	/** Whether the filter is enabled */
	filterEnabled: boolean;
};

/** A source filter's enable state has changed. */
export const SourceFilterEnableStateChanged: ObsEvent<
	SourceFilterEnableStateChangedPayload
> = new ObsEvent<SourceFilterEnableStateChangedPayload>(
	"SourceFilterEnableStateChanged",
	1 << 5,
);

/** Payload for {@link SourceFilterListReindexed} */
export type SourceFilterListReindexedPayload = {
	/** Name of the source */
	sourceName: string;
	/** Array of filter objects */
	filters: object[];
};

/** A source's filter list has been reindexed. */
export const SourceFilterListReindexed: ObsEvent<
	SourceFilterListReindexedPayload
> = new ObsEvent<SourceFilterListReindexedPayload>(
	"SourceFilterListReindexed",
	1 << 5,
);

/** Payload for {@link SourceFilterNameChanged} */
export type SourceFilterNameChangedPayload = {
	/** The source the filter is on */
	sourceName: string;
	/** Old name of the filter */
	oldFilterName: string;
	/** New name of the filter */
	filterName: string;
};

/** The name of a source filter has changed. */
export const SourceFilterNameChanged: ObsEvent<SourceFilterNameChangedPayload> =
	new ObsEvent<SourceFilterNameChangedPayload>(
		"SourceFilterNameChanged",
		1 << 5,
	);

/** Payload for {@link SourceFilterRemoved} */
export type SourceFilterRemovedPayload = {
	/** Name of the source the filter was on */
	sourceName: string;
	/** Name of the filter */
	filterName: string;
};

/** A filter has been removed from a source. */
export const SourceFilterRemoved: ObsEvent<SourceFilterRemovedPayload> =
	new ObsEvent<SourceFilterRemovedPayload>("SourceFilterRemoved", 1 << 5);

/** Payload for {@link SourceFilterSettingsChanged} */
export type SourceFilterSettingsChangedPayload = {
	/** Name of the source the filter is on */
	sourceName: string;
	/** Name of the filter */
	filterName: string;
	/** New settings object of the filter */
	filterSettings: object;
};

/** An source filter's settings have changed (been updated). */
export const SourceFilterSettingsChanged: ObsEvent<
	SourceFilterSettingsChangedPayload
> = new ObsEvent<SourceFilterSettingsChangedPayload>(
	"SourceFilterSettingsChanged",
	1 << 5,
);

/** Payload for {@link StreamStateChanged} */
export type StreamStateChangedPayload = {
	/** Whether the output is active */
	outputActive: boolean;
	/** The specific state of the output */
	outputState: string;
};

/** The state of the stream output has changed. */
export const StreamStateChanged: ObsEvent<StreamStateChangedPayload> =
	new ObsEvent<StreamStateChangedPayload>("StreamStateChanged", 1 << 6);

/** Payload for {@link StudioModeStateChanged} */
export type StudioModeStateChangedPayload = {
	/** True == Enabled, False == Disabled */
	studioModeEnabled: boolean;
};

/** Studio mode has been enabled or disabled. */
export const StudioModeStateChanged: ObsEvent<StudioModeStateChangedPayload> =
	new ObsEvent<StudioModeStateChangedPayload>(
		"StudioModeStateChanged",
		1 << 10,
	);

/** Payload for {@link VendorEvent} */
export type VendorEventPayload = {
	/** Name of the vendor emitting the event */
	vendorName: string;
	/** Vendor-provided event typedef */
	eventType: string;
	/** Vendor-provided event data. {} if event does not provide any data */
	eventData: object;
};

/** An event has been emitted from a vendor.

A vendor is a unique name registered by a third-party plugin or script, which allows for custom requests and events to be added to obs-websocket.
If a plugin or script implements vendor requests or events, documentation is expected to be provided with them. */
export const VendorEvent: ObsEvent<VendorEventPayload> = new ObsEvent<
	VendorEventPayload
>("VendorEvent", 1 << 0);

/** Payload for {@link VirtualcamStateChanged} */
export type VirtualcamStateChangedPayload = {
	/** Whether the output is active */
	outputActive: boolean;
	/** The specific state of the output */
	outputState: string;
};

/** The state of the virtualcam output has changed. */
export const VirtualcamStateChanged: ObsEvent<VirtualcamStateChangedPayload> =
	new ObsEvent<VirtualcamStateChangedPayload>("VirtualcamStateChanged", 1 << 6);
