// This file is @generated by scripts/requests.ts

export class ObsRequest<Request, Response> {
	type: string;
	constructor(name: string) {
		this.type = name;
	}
}

/** Request for {@link BroadcastCustomEvent} */
export type BroadcastCustomEventRequest = {
	/** Data payload to emit to all receivers */
	eventData: object;
};

/** Broadcasts a `CustomEvent` to all WebSocket clients. Receivers are clients which are identified and subscribed. */
export const BroadcastCustomEvent: ObsRequest<
	BroadcastCustomEventRequest,
	undefined
> = new ObsRequest<BroadcastCustomEventRequest, undefined>(
	"BroadcastCustomEvent",
);

/** Request for {@link CallVendorRequest} */
export type CallVendorRequestRequest = {
	/** Name of the vendor to use */
	vendorName: string;
	/** The request type to call */
	requestType: string;
	/** Object containing appropriate request data */
	requestData?: object;
};

/** Response for {@link CallVendorRequest} */
export type CallVendorRequestResponse = {
	/** Echoed of `vendorName` */
	vendorName: string;
	/** Echoed of `requestType` */
	requestType: string;
	/** Object containing appropriate response data. {} if request does not provide any response data */
	responseData: object;
};

/** Call a request registered to a vendor.

A vendor is a unique name registered by a third-party plugin or script, which allows for custom requests and events to be added to obs-websocket.
If a plugin or script implements vendor requests or events, documentation is expected to be provided with them. */
export const CallVendorRequest: ObsRequest<
	CallVendorRequestRequest,
	CallVendorRequestResponse
> = new ObsRequest<CallVendorRequestRequest, CallVendorRequestResponse>(
	"CallVendorRequest",
);

/** Request for {@link CreateInput} */
export type CreateInputRequest = {
	/** Name of the scene to add the input to as a scene item */
	sceneName?: string;
	/** UUID of the scene to add the input to as a scene item */
	sceneUuid?: string;
	/** Name of the new input to created */
	inputName: string;
	/** The kind of input to be created */
	inputKind: string;
	/** Settings object to initialize the input with */
	inputSettings?: object;
	/** Whether to set the created scene item to enabled or disabled */
	sceneItemEnabled?: boolean;
};

/** Response for {@link CreateInput} */
export type CreateInputResponse = {
	/** UUID of the newly created input */
	inputUuid: string;
	/** ID of the newly created scene item */
	sceneItemId: number;
};

/** Creates a new input, adding it as a scene item to the specified scene. */
export const CreateInput: ObsRequest<CreateInputRequest, CreateInputResponse> =
	new ObsRequest<CreateInputRequest, CreateInputResponse>("CreateInput");

/** Request for {@link CreateProfile} */
export type CreateProfileRequest = {
	/** Name for the new profile */
	profileName: string;
};

/** Creates a new profile, switching to it in the process */
export const CreateProfile: ObsRequest<CreateProfileRequest, undefined> =
	new ObsRequest<CreateProfileRequest, undefined>("CreateProfile");

/** Request for {@link CreateRecordChapter} */
export type CreateRecordChapterRequest = {
	/** Name of the new chapter */
	chapterName?: string;
};

/** Adds a new chapter marker to the file currently being recorded.

Note: As of OBS 30.2.0, the only file format supporting this feature is Hybrid MP4. */
export const CreateRecordChapter: ObsRequest<
	CreateRecordChapterRequest,
	undefined
> = new ObsRequest<CreateRecordChapterRequest, undefined>(
	"CreateRecordChapter",
);

/** Request for {@link CreateScene} */
export type CreateSceneRequest = {
	/** Name for the new scene */
	sceneName: string;
};

/** Response for {@link CreateScene} */
export type CreateSceneResponse = {
	/** UUID of the created scene */
	sceneUuid: string;
};

/** Creates a new scene in OBS. */
export const CreateScene: ObsRequest<CreateSceneRequest, CreateSceneResponse> =
	new ObsRequest<CreateSceneRequest, CreateSceneResponse>("CreateScene");

/** Request for {@link CreateSceneCollection} */
export type CreateSceneCollectionRequest = {
	/** Name for the new scene collection */
	sceneCollectionName: string;
};

/** Creates a new scene collection, switching to it in the process.

Note: This will block until the collection has finished changing. */
export const CreateSceneCollection: ObsRequest<
	CreateSceneCollectionRequest,
	undefined
> = new ObsRequest<CreateSceneCollectionRequest, undefined>(
	"CreateSceneCollection",
);

/** Request for {@link CreateSceneItem} */
export type CreateSceneItemRequest = {
	/** Name of the scene to create the new item in */
	sceneName?: string;
	/** UUID of the scene to create the new item in */
	sceneUuid?: string;
	/** Name of the source to add to the scene */
	sourceName?: string;
	/** UUID of the source to add to the scene */
	sourceUuid?: string;
	/** Enable state to apply to the scene item on creation */
	sceneItemEnabled?: boolean;
};

/** Response for {@link CreateSceneItem} */
export type CreateSceneItemResponse = {
	/** Numeric ID of the scene item */
	sceneItemId: number;
};

/** Creates a new scene item using a source.

Scenes only */
export const CreateSceneItem: ObsRequest<
	CreateSceneItemRequest,
	CreateSceneItemResponse
> = new ObsRequest<CreateSceneItemRequest, CreateSceneItemResponse>(
	"CreateSceneItem",
);

/** Request for {@link CreateSourceFilter} */
export type CreateSourceFilterRequest = {
	/** Name of the source to add the filter to */
	sourceName?: string;
	/** UUID of the source to add the filter to */
	sourceUuid?: string;
	/** Name of the new filter to be created */
	filterName: string;
	/** The kind of filter to be created */
	filterKind: string;
	/** Settings object to initialize the filter with */
	filterSettings?: object;
};

/** Creates a new filter, adding it to the specified source. */
export const CreateSourceFilter: ObsRequest<
	CreateSourceFilterRequest,
	undefined
> = new ObsRequest<CreateSourceFilterRequest, undefined>("CreateSourceFilter");

/** Request for {@link DuplicateSceneItem} */
export type DuplicateSceneItemRequest = {
	/** Name of the scene the item is in */
	sceneName?: string;
	/** UUID of the scene the item is in */
	sceneUuid?: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
	/** Name of the scene to create the duplicated item in */
	destinationSceneName?: string;
	/** UUID of the scene to create the duplicated item in */
	destinationSceneUuid?: string;
};

/** Response for {@link DuplicateSceneItem} */
export type DuplicateSceneItemResponse = {
	/** Numeric ID of the duplicated scene item */
	sceneItemId: number;
};

/** Duplicates a scene item, copying all transform and crop info.

Scenes only */
export const DuplicateSceneItem: ObsRequest<
	DuplicateSceneItemRequest,
	DuplicateSceneItemResponse
> = new ObsRequest<DuplicateSceneItemRequest, DuplicateSceneItemResponse>(
	"DuplicateSceneItem",
);

/** Response for {@link GetCurrentPreviewScene} */
export type GetCurrentPreviewSceneResponse = {
	/** Current preview scene name */
	sceneName: string;
	/** Current preview scene UUID */
	sceneUuid: string;
	/** Current preview scene name */
	currentPreviewSceneName: string;
	/** Current preview scene UUID */
	currentPreviewSceneUuid: string;
};

/** Gets the current preview scene.

Only available when studio mode is enabled.

Note: This request is slated to have the `currentPreview`-prefixed fields removed from in an upcoming RPC version. */
export const GetCurrentPreviewScene: ObsRequest<
	undefined,
	GetCurrentPreviewSceneResponse
> = new ObsRequest<undefined, GetCurrentPreviewSceneResponse>(
	"GetCurrentPreviewScene",
);

/** Response for {@link GetCurrentProgramScene} */
export type GetCurrentProgramSceneResponse = {
	/** Current program scene name */
	sceneName: string;
	/** Current program scene UUID */
	sceneUuid: string;
	/** Current program scene name (Deprecated) */
	currentProgramSceneName: string;
	/** Current program scene UUID (Deprecated) */
	currentProgramSceneUuid: string;
};

/** Gets the current program scene.

Note: This request is slated to have the `currentProgram`-prefixed fields removed from in an upcoming RPC version. */
export const GetCurrentProgramScene: ObsRequest<
	undefined,
	GetCurrentProgramSceneResponse
> = new ObsRequest<undefined, GetCurrentProgramSceneResponse>(
	"GetCurrentProgramScene",
);

/** Response for {@link GetCurrentSceneTransition} */
export type GetCurrentSceneTransitionResponse = {
	/** Name of the transition */
	transitionName: string;
	/** UUID of the transition */
	transitionUuid: string;
	/** Kind of the transition */
	transitionKind: string;
	/** Whether the transition uses a fixed (unconfigurable) duration */
	transitionFixed: boolean;
	/** Configured transition duration in milliseconds. `null` if transition is fixed */
	transitionDuration: number;
	/** Whether the transition supports being configured */
	transitionConfigurable: boolean;
	/** Object of settings for the transition. `null` if transition is not configurable */
	transitionSettings: object;
};

/** Gets information about the current scene transition. */
export const GetCurrentSceneTransition: ObsRequest<
	undefined,
	GetCurrentSceneTransitionResponse
> = new ObsRequest<undefined, GetCurrentSceneTransitionResponse>(
	"GetCurrentSceneTransition",
);

/** Response for {@link GetCurrentSceneTransitionCursor} */
export type GetCurrentSceneTransitionCursorResponse = {
	/** Cursor position, between 0.0 and 1.0 */
	transitionCursor: number;
};

/** Gets the cursor position of the current scene transition.

Note: `transitionCursor` will return 1.0 when the transition is inactive. */
export const GetCurrentSceneTransitionCursor: ObsRequest<
	undefined,
	GetCurrentSceneTransitionCursorResponse
> = new ObsRequest<undefined, GetCurrentSceneTransitionCursorResponse>(
	"GetCurrentSceneTransitionCursor",
);

/** Response for {@link GetGroupList} */
export type GetGroupListResponse = {
	/** Array of group names */
	groups: string[];
};

/** Gets an array of all groups in OBS.

Groups in OBS are actually scenes, but renamed and modified. In obs-websocket, we treat them as scenes where we can. */
export const GetGroupList: ObsRequest<undefined, GetGroupListResponse> =
	new ObsRequest<undefined, GetGroupListResponse>("GetGroupList");

/** Request for {@link GetGroupSceneItemList} */
export type GetGroupSceneItemListRequest = {
	/** Name of the group to get the items of */
	sceneName?: string;
	/** UUID of the group to get the items of */
	sceneUuid?: string;
};

/** Response for {@link GetGroupSceneItemList} */
export type GetGroupSceneItemListResponse = {
	/** Array of scene items in the group */
	sceneItems: object[];
};

/** Basically GetSceneItemList, but for groups.

Using groups at all in OBS is discouraged, as they are very broken under the hood. Please use nested scenes instead.

Groups only */
export const GetGroupSceneItemList: ObsRequest<
	GetGroupSceneItemListRequest,
	GetGroupSceneItemListResponse
> = new ObsRequest<GetGroupSceneItemListRequest, GetGroupSceneItemListResponse>(
	"GetGroupSceneItemList",
);

/** Response for {@link GetHotkeyList} */
export type GetHotkeyListResponse = {
	/** Array of hotkey names */
	hotkeys: string[];
};

/** Gets an array of all hotkey names in OBS.

Note: Hotkey functionality in obs-websocket comes as-is, and we do not guarantee support if things are broken. In 9/10 usages of hotkey requests, there exists a better, more reliable method via other requests. */
export const GetHotkeyList: ObsRequest<undefined, GetHotkeyListResponse> =
	new ObsRequest<undefined, GetHotkeyListResponse>("GetHotkeyList");

/** Request for {@link GetInputAudioBalance} */
export type GetInputAudioBalanceRequest = {
	/** Name of the input to get the audio balance of */
	inputName?: string;
	/** UUID of the input to get the audio balance of */
	inputUuid?: string;
};

/** Response for {@link GetInputAudioBalance} */
export type GetInputAudioBalanceResponse = {
	/** Audio balance value from 0.0-1.0 */
	inputAudioBalance: number;
};

/** Gets the audio balance of an input. */
export const GetInputAudioBalance: ObsRequest<
	GetInputAudioBalanceRequest,
	GetInputAudioBalanceResponse
> = new ObsRequest<GetInputAudioBalanceRequest, GetInputAudioBalanceResponse>(
	"GetInputAudioBalance",
);

/** Request for {@link GetInputAudioMonitorType} */
export type GetInputAudioMonitorTypeRequest = {
	/** Name of the input to get the audio monitor type of */
	inputName?: string;
	/** UUID of the input to get the audio monitor type of */
	inputUuid?: string;
};

/** Response for {@link GetInputAudioMonitorType} */
export type GetInputAudioMonitorTypeResponse = {
	/** Audio monitor type */
	monitorType: string;
};

/** Gets the audio monitor type of an input.

The available audio monitor types are:

- `OBS_MONITORING_TYPE_NONE`
- `OBS_MONITORING_TYPE_MONITOR_ONLY`
- `OBS_MONITORING_TYPE_MONITOR_AND_OUTPUT` */
export const GetInputAudioMonitorType: ObsRequest<
	GetInputAudioMonitorTypeRequest,
	GetInputAudioMonitorTypeResponse
> = new ObsRequest<
	GetInputAudioMonitorTypeRequest,
	GetInputAudioMonitorTypeResponse
>("GetInputAudioMonitorType");

/** Request for {@link GetInputAudioSyncOffset} */
export type GetInputAudioSyncOffsetRequest = {
	/** Name of the input to get the audio sync offset of */
	inputName?: string;
	/** UUID of the input to get the audio sync offset of */
	inputUuid?: string;
};

/** Response for {@link GetInputAudioSyncOffset} */
export type GetInputAudioSyncOffsetResponse = {
	/** Audio sync offset in milliseconds */
	inputAudioSyncOffset: number;
};

/** Gets the audio sync offset of an input.

Note: The audio sync offset can be negative too! */
export const GetInputAudioSyncOffset: ObsRequest<
	GetInputAudioSyncOffsetRequest,
	GetInputAudioSyncOffsetResponse
> = new ObsRequest<
	GetInputAudioSyncOffsetRequest,
	GetInputAudioSyncOffsetResponse
>("GetInputAudioSyncOffset");

/** Request for {@link GetInputAudioTracks} */
export type GetInputAudioTracksRequest = {
	/** Name of the input */
	inputName?: string;
	/** UUID of the input */
	inputUuid?: string;
};

/** Response for {@link GetInputAudioTracks} */
export type GetInputAudioTracksResponse = {
	/** Object of audio tracks and associated enable states */
	inputAudioTracks: object;
};

/** Gets the enable state of all audio tracks of an input. */
export const GetInputAudioTracks: ObsRequest<
	GetInputAudioTracksRequest,
	GetInputAudioTracksResponse
> = new ObsRequest<GetInputAudioTracksRequest, GetInputAudioTracksResponse>(
	"GetInputAudioTracks",
);

/** Request for {@link GetInputDefaultSettings} */
export type GetInputDefaultSettingsRequest = {
	/** Input kind to get the default settings for */
	inputKind: string;
};

/** Response for {@link GetInputDefaultSettings} */
export type GetInputDefaultSettingsResponse = {
	/** Object of default settings for the input kind */
	defaultInputSettings: object;
};

/** Gets the default settings for an input kind. */
export const GetInputDefaultSettings: ObsRequest<
	GetInputDefaultSettingsRequest,
	GetInputDefaultSettingsResponse
> = new ObsRequest<
	GetInputDefaultSettingsRequest,
	GetInputDefaultSettingsResponse
>("GetInputDefaultSettings");

/** Request for {@link GetInputDeinterlaceFieldOrder} */
export type GetInputDeinterlaceFieldOrderRequest = {
	/** Name of the input */
	inputName?: string;
	/** UUID of the input */
	inputUuid?: string;
};

/** Response for {@link GetInputDeinterlaceFieldOrder} */
export type GetInputDeinterlaceFieldOrderResponse = {
	/** Deinterlace field order of the input */
	inputDeinterlaceFieldOrder: string;
};

/** Gets the deinterlace field order of an input.

Deinterlace Field Orders:

- `OBS_DEINTERLACE_FIELD_ORDER_TOP`
- `OBS_DEINTERLACE_FIELD_ORDER_BOTTOM`

Note: Deinterlacing functionality is restricted to async inputs only. */
export const GetInputDeinterlaceFieldOrder: ObsRequest<
	GetInputDeinterlaceFieldOrderRequest,
	GetInputDeinterlaceFieldOrderResponse
> = new ObsRequest<
	GetInputDeinterlaceFieldOrderRequest,
	GetInputDeinterlaceFieldOrderResponse
>("GetInputDeinterlaceFieldOrder");

/** Request for {@link GetInputDeinterlaceMode} */
export type GetInputDeinterlaceModeRequest = {
	/** Name of the input */
	inputName?: string;
	/** UUID of the input */
	inputUuid?: string;
};

/** Response for {@link GetInputDeinterlaceMode} */
export type GetInputDeinterlaceModeResponse = {
	/** Deinterlace mode of the input */
	inputDeinterlaceMode: string;
};

/** Gets the deinterlace mode of an input.

Deinterlace Modes:

- `OBS_DEINTERLACE_MODE_DISABLE`
- `OBS_DEINTERLACE_MODE_DISCARD`
- `OBS_DEINTERLACE_MODE_RETRO`
- `OBS_DEINTERLACE_MODE_BLEND`
- `OBS_DEINTERLACE_MODE_BLEND_2X`
- `OBS_DEINTERLACE_MODE_LINEAR`
- `OBS_DEINTERLACE_MODE_LINEAR_2X`
- `OBS_DEINTERLACE_MODE_YADIF`
- `OBS_DEINTERLACE_MODE_YADIF_2X`

Note: Deinterlacing functionality is restricted to async inputs only. */
export const GetInputDeinterlaceMode: ObsRequest<
	GetInputDeinterlaceModeRequest,
	GetInputDeinterlaceModeResponse
> = new ObsRequest<
	GetInputDeinterlaceModeRequest,
	GetInputDeinterlaceModeResponse
>("GetInputDeinterlaceMode");

/** Request for {@link GetInputKindList} */
export type GetInputKindListRequest = {
	/** True == Return all kinds as unversioned, False == Return with version suffixes (if available) */
	unversioned?: boolean;
};

/** Response for {@link GetInputKindList} */
export type GetInputKindListResponse = {
	/** Array of input kinds */
	inputKinds: string[];
};

/** Gets an array of all available input kinds in OBS. */
export const GetInputKindList: ObsRequest<
	GetInputKindListRequest,
	GetInputKindListResponse
> = new ObsRequest<GetInputKindListRequest, GetInputKindListResponse>(
	"GetInputKindList",
);

/** Request for {@link GetInputList} */
export type GetInputListRequest = {
	/** Restrict the array to only inputs of the specified kind */
	inputKind?: string;
};

/** Response for {@link GetInputList} */
export type GetInputListResponse = {
	/** Array of inputs */
	inputs: object[];
};

/** Gets an array of all inputs in OBS. */
export const GetInputList: ObsRequest<
	GetInputListRequest,
	GetInputListResponse
> = new ObsRequest<GetInputListRequest, GetInputListResponse>("GetInputList");

/** Request for {@link GetInputMute} */
export type GetInputMuteRequest = {
	/** Name of input to get the mute state of */
	inputName?: string;
	/** UUID of input to get the mute state of */
	inputUuid?: string;
};

/** Response for {@link GetInputMute} */
export type GetInputMuteResponse = {
	/** Whether the input is muted */
	inputMuted: boolean;
};

/** Gets the audio mute state of an input. */
export const GetInputMute: ObsRequest<
	GetInputMuteRequest,
	GetInputMuteResponse
> = new ObsRequest<GetInputMuteRequest, GetInputMuteResponse>("GetInputMute");

/** Request for {@link GetInputPropertiesListPropertyItems} */
export type GetInputPropertiesListPropertyItemsRequest = {
	/** Name of the input */
	inputName?: string;
	/** UUID of the input */
	inputUuid?: string;
	/** Name of the list property to get the items of */
	propertyName: string;
};

/** Response for {@link GetInputPropertiesListPropertyItems} */
export type GetInputPropertiesListPropertyItemsResponse = {
	/** Array of items in the list property */
	propertyItems: object[];
};

/** Gets the items of a list property from an input's properties.

Note: Use this in cases where an input provides a dynamic, selectable list of items. For example, display capture, where it provides a list of available displays. */
export const GetInputPropertiesListPropertyItems: ObsRequest<
	GetInputPropertiesListPropertyItemsRequest,
	GetInputPropertiesListPropertyItemsResponse
> = new ObsRequest<
	GetInputPropertiesListPropertyItemsRequest,
	GetInputPropertiesListPropertyItemsResponse
>("GetInputPropertiesListPropertyItems");

/** Request for {@link GetInputSettings} */
export type GetInputSettingsRequest = {
	/** Name of the input to get the settings of */
	inputName?: string;
	/** UUID of the input to get the settings of */
	inputUuid?: string;
};

/** Response for {@link GetInputSettings} */
export type GetInputSettingsResponse = {
	/** Object of settings for the input */
	inputSettings: object;
	/** The kind of the input */
	inputKind: string;
};

/** Gets the settings of an input.

Note: Does not include defaults. To create the entire settings object, overlay `inputSettings` over the `defaultInputSettings` provided by `GetInputDefaultSettings`. */
export const GetInputSettings: ObsRequest<
	GetInputSettingsRequest,
	GetInputSettingsResponse
> = new ObsRequest<GetInputSettingsRequest, GetInputSettingsResponse>(
	"GetInputSettings",
);

/** Request for {@link GetInputVolume} */
export type GetInputVolumeRequest = {
	/** Name of the input to get the volume of */
	inputName?: string;
	/** UUID of the input to get the volume of */
	inputUuid?: string;
};

/** Response for {@link GetInputVolume} */
export type GetInputVolumeResponse = {
	/** Volume setting in mul */
	inputVolumeMul: number;
	/** Volume setting in dB */
	inputVolumeDb: number;
};

/** Gets the current volume setting of an input. */
export const GetInputVolume: ObsRequest<
	GetInputVolumeRequest,
	GetInputVolumeResponse
> = new ObsRequest<GetInputVolumeRequest, GetInputVolumeResponse>(
	"GetInputVolume",
);

/** Response for {@link GetLastReplayBufferReplay} */
export type GetLastReplayBufferReplayResponse = {
	/** File path */
	savedReplayPath: string;
};

/** Gets the filename of the last replay buffer save file. */
export const GetLastReplayBufferReplay: ObsRequest<
	undefined,
	GetLastReplayBufferReplayResponse
> = new ObsRequest<undefined, GetLastReplayBufferReplayResponse>(
	"GetLastReplayBufferReplay",
);

/** Request for {@link GetMediaInputStatus} */
export type GetMediaInputStatusRequest = {
	/** Name of the media input */
	inputName?: string;
	/** UUID of the media input */
	inputUuid?: string;
};

/** Response for {@link GetMediaInputStatus} */
export type GetMediaInputStatusResponse = {
	/** State of the media input */
	mediaState: string;
	/** Total duration of the playing media in milliseconds. `null` if not playing */
	mediaDuration: number;
	/** Position of the cursor in milliseconds. `null` if not playing */
	mediaCursor: number;
};

/** Gets the status of a media input.

Media States:

- `OBS_MEDIA_STATE_NONE`
- `OBS_MEDIA_STATE_PLAYING`
- `OBS_MEDIA_STATE_OPENING`
- `OBS_MEDIA_STATE_BUFFERING`
- `OBS_MEDIA_STATE_PAUSED`
- `OBS_MEDIA_STATE_STOPPED`
- `OBS_MEDIA_STATE_ENDED`
- `OBS_MEDIA_STATE_ERROR` */
export const GetMediaInputStatus: ObsRequest<
	GetMediaInputStatusRequest,
	GetMediaInputStatusResponse
> = new ObsRequest<GetMediaInputStatusRequest, GetMediaInputStatusResponse>(
	"GetMediaInputStatus",
);

/** Response for {@link GetMonitorList} */
export type GetMonitorListResponse = {
	/** a list of detected monitors with some information */
	monitors: object[];
};

/** Gets a list of connected monitors and information about them. */
export const GetMonitorList: ObsRequest<undefined, GetMonitorListResponse> =
	new ObsRequest<undefined, GetMonitorListResponse>("GetMonitorList");

/** Response for {@link GetOutputList} */
export type GetOutputListResponse = {
	/** Array of outputs */
	outputs: object[];
};

/** Gets the list of available outputs. */
export const GetOutputList: ObsRequest<undefined, GetOutputListResponse> =
	new ObsRequest<undefined, GetOutputListResponse>("GetOutputList");

/** Request for {@link GetOutputSettings} */
export type GetOutputSettingsRequest = {
	/** Output name */
	outputName: string;
};

/** Response for {@link GetOutputSettings} */
export type GetOutputSettingsResponse = {
	/** Output settings */
	outputSettings: object;
};

/** Gets the settings of an output. */
export const GetOutputSettings: ObsRequest<
	GetOutputSettingsRequest,
	GetOutputSettingsResponse
> = new ObsRequest<GetOutputSettingsRequest, GetOutputSettingsResponse>(
	"GetOutputSettings",
);

/** Request for {@link GetOutputStatus} */
export type GetOutputStatusRequest = {
	/** Output name */
	outputName: string;
};

/** Response for {@link GetOutputStatus} */
export type GetOutputStatusResponse = {
	/** Whether the output is active */
	outputActive: boolean;
	/** Whether the output is reconnecting */
	outputReconnecting: boolean;
	/** Current formatted timecode string for the output */
	outputTimecode: string;
	/** Current duration in milliseconds for the output */
	outputDuration: number;
	/** Congestion of the output */
	outputCongestion: number;
	/** Number of bytes sent by the output */
	outputBytes: number;
	/** Number of frames skipped by the output's process */
	outputSkippedFrames: number;
	/** Total number of frames delivered by the output's process */
	outputTotalFrames: number;
};

/** Gets the status of an output. */
export const GetOutputStatus: ObsRequest<
	GetOutputStatusRequest,
	GetOutputStatusResponse
> = new ObsRequest<GetOutputStatusRequest, GetOutputStatusResponse>(
	"GetOutputStatus",
);

/** Request for {@link GetPersistentData} */
export type GetPersistentDataRequest = {
	/** The data realm to select. `OBS_WEBSOCKET_DATA_REALM_GLOBAL` or `OBS_WEBSOCKET_DATA_REALM_PROFILE` */
	realm: string;
	/** The name of the slot to retrieve data from */
	slotName: string;
};

/** Response for {@link GetPersistentData} */
export type GetPersistentDataResponse = {
	/** Value associated with the slot. `null` if not set */
	slotValue: unknown;
};

/** Gets the value of a "slot" from the selected persistent data realm. */
export const GetPersistentData: ObsRequest<
	GetPersistentDataRequest,
	GetPersistentDataResponse
> = new ObsRequest<GetPersistentDataRequest, GetPersistentDataResponse>(
	"GetPersistentData",
);

/** Response for {@link GetProfileList} */
export type GetProfileListResponse = {
	/** The name of the current profile */
	currentProfileName: string;
	/** Array of all available profiles */
	profiles: string[];
};

/** Gets an array of all profiles */
export const GetProfileList: ObsRequest<undefined, GetProfileListResponse> =
	new ObsRequest<undefined, GetProfileListResponse>("GetProfileList");

/** Request for {@link GetProfileParameter} */
export type GetProfileParameterRequest = {
	/** Category of the parameter to get */
	parameterCategory: string;
	/** Name of the parameter to get */
	parameterName: string;
};

/** Response for {@link GetProfileParameter} */
export type GetProfileParameterResponse = {
	/** Value associated with the parameter. `null` if not set and no default */
	parameterValue: string;
	/** Default value associated with the parameter. `null` if no default */
	defaultParameterValue: string;
};

/** Gets a parameter from the current profile's configuration. */
export const GetProfileParameter: ObsRequest<
	GetProfileParameterRequest,
	GetProfileParameterResponse
> = new ObsRequest<GetProfileParameterRequest, GetProfileParameterResponse>(
	"GetProfileParameter",
);

/** Response for {@link GetRecordDirectory} */
export type GetRecordDirectoryResponse = {
	/** Output directory */
	recordDirectory: string;
};

/** Gets the current directory that the record output is set to. */
export const GetRecordDirectory: ObsRequest<
	undefined,
	GetRecordDirectoryResponse
> = new ObsRequest<undefined, GetRecordDirectoryResponse>("GetRecordDirectory");

/** Response for {@link GetRecordStatus} */
export type GetRecordStatusResponse = {
	/** Whether the output is active */
	outputActive: boolean;
	/** Whether the output is paused */
	outputPaused: boolean;
	/** Current formatted timecode string for the output */
	outputTimecode: string;
	/** Current duration in milliseconds for the output */
	outputDuration: number;
	/** Number of bytes sent by the output */
	outputBytes: number;
};

/** Gets the status of the record output. */
export const GetRecordStatus: ObsRequest<undefined, GetRecordStatusResponse> =
	new ObsRequest<undefined, GetRecordStatusResponse>("GetRecordStatus");

/** Response for {@link GetReplayBufferStatus} */
export type GetReplayBufferStatusResponse = {
	/** Whether the output is active */
	outputActive: boolean;
};

/** Gets the status of the replay buffer output. */
export const GetReplayBufferStatus: ObsRequest<
	undefined,
	GetReplayBufferStatusResponse
> = new ObsRequest<undefined, GetReplayBufferStatusResponse>(
	"GetReplayBufferStatus",
);

/** Response for {@link GetSceneCollectionList} */
export type GetSceneCollectionListResponse = {
	/** The name of the current scene collection */
	currentSceneCollectionName: string;
	/** Array of all available scene collections */
	sceneCollections: string[];
};

/** Gets an array of all scene collections */
export const GetSceneCollectionList: ObsRequest<
	undefined,
	GetSceneCollectionListResponse
> = new ObsRequest<undefined, GetSceneCollectionListResponse>(
	"GetSceneCollectionList",
);

/** Request for {@link GetSceneItemBlendMode} */
export type GetSceneItemBlendModeRequest = {
	/** Name of the scene the item is in */
	sceneName?: string;
	/** UUID of the scene the item is in */
	sceneUuid?: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
};

/** Response for {@link GetSceneItemBlendMode} */
export type GetSceneItemBlendModeResponse = {
	/** Current blend mode */
	sceneItemBlendMode: string;
};

/** Gets the blend mode of a scene item.

Blend modes:

- `OBS_BLEND_NORMAL`
- `OBS_BLEND_ADDITIVE`
- `OBS_BLEND_SUBTRACT`
- `OBS_BLEND_SCREEN`
- `OBS_BLEND_MULTIPLY`
- `OBS_BLEND_LIGHTEN`
- `OBS_BLEND_DARKEN`

Scenes and Groups */
export const GetSceneItemBlendMode: ObsRequest<
	GetSceneItemBlendModeRequest,
	GetSceneItemBlendModeResponse
> = new ObsRequest<GetSceneItemBlendModeRequest, GetSceneItemBlendModeResponse>(
	"GetSceneItemBlendMode",
);

/** Request for {@link GetSceneItemEnabled} */
export type GetSceneItemEnabledRequest = {
	/** Name of the scene the item is in */
	sceneName?: string;
	/** UUID of the scene the item is in */
	sceneUuid?: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
};

/** Response for {@link GetSceneItemEnabled} */
export type GetSceneItemEnabledResponse = {
	/** Whether the scene item is enabled. `true` for enabled, `false` for disabled */
	sceneItemEnabled: boolean;
};

/** Gets the enable state of a scene item.

Scenes and Groups */
export const GetSceneItemEnabled: ObsRequest<
	GetSceneItemEnabledRequest,
	GetSceneItemEnabledResponse
> = new ObsRequest<GetSceneItemEnabledRequest, GetSceneItemEnabledResponse>(
	"GetSceneItemEnabled",
);

/** Request for {@link GetSceneItemId} */
export type GetSceneItemIdRequest = {
	/** Name of the scene or group to search in */
	sceneName?: string;
	/** UUID of the scene or group to search in */
	sceneUuid?: string;
	/** Name of the source to find */
	sourceName: string;
	/** Number of matches to skip during search. >= 0 means first forward. -1 means last (top) item */
	searchOffset?: number;
};

/** Response for {@link GetSceneItemId} */
export type GetSceneItemIdResponse = {
	/** Numeric ID of the scene item */
	sceneItemId: number;
};

/** Searches a scene for a source, and returns its id.

Scenes and Groups */
export const GetSceneItemId: ObsRequest<
	GetSceneItemIdRequest,
	GetSceneItemIdResponse
> = new ObsRequest<GetSceneItemIdRequest, GetSceneItemIdResponse>(
	"GetSceneItemId",
);

/** Request for {@link GetSceneItemIndex} */
export type GetSceneItemIndexRequest = {
	/** Name of the scene the item is in */
	sceneName?: string;
	/** UUID of the scene the item is in */
	sceneUuid?: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
};

/** Response for {@link GetSceneItemIndex} */
export type GetSceneItemIndexResponse = {
	/** Index position of the scene item */
	sceneItemIndex: number;
};

/** Gets the index position of a scene item in a scene.

An index of 0 is at the bottom of the source list in the UI.

Scenes and Groups */
export const GetSceneItemIndex: ObsRequest<
	GetSceneItemIndexRequest,
	GetSceneItemIndexResponse
> = new ObsRequest<GetSceneItemIndexRequest, GetSceneItemIndexResponse>(
	"GetSceneItemIndex",
);

/** Request for {@link GetSceneItemList} */
export type GetSceneItemListRequest = {
	/** Name of the scene to get the items of */
	sceneName?: string;
	/** UUID of the scene to get the items of */
	sceneUuid?: string;
};

/** Response for {@link GetSceneItemList} */
export type GetSceneItemListResponse = {
	/** Array of scene items in the scene */
	sceneItems: object[];
};

/** Gets a list of all scene items in a scene.

Scenes only */
export const GetSceneItemList: ObsRequest<
	GetSceneItemListRequest,
	GetSceneItemListResponse
> = new ObsRequest<GetSceneItemListRequest, GetSceneItemListResponse>(
	"GetSceneItemList",
);

/** Request for {@link GetSceneItemLocked} */
export type GetSceneItemLockedRequest = {
	/** Name of the scene the item is in */
	sceneName?: string;
	/** UUID of the scene the item is in */
	sceneUuid?: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
};

/** Response for {@link GetSceneItemLocked} */
export type GetSceneItemLockedResponse = {
	/** Whether the scene item is locked. `true` for locked, `false` for unlocked */
	sceneItemLocked: boolean;
};

/** Gets the lock state of a scene item.

Scenes and Groups */
export const GetSceneItemLocked: ObsRequest<
	GetSceneItemLockedRequest,
	GetSceneItemLockedResponse
> = new ObsRequest<GetSceneItemLockedRequest, GetSceneItemLockedResponse>(
	"GetSceneItemLocked",
);

/** Request for {@link GetSceneItemSource} */
export type GetSceneItemSourceRequest = {
	/** Name of the scene the item is in */
	sceneName?: string;
	/** UUID of the scene the item is in */
	sceneUuid?: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
};

/** Response for {@link GetSceneItemSource} */
export type GetSceneItemSourceResponse = {
	/** Name of the source associated with the scene item */
	sourceName: string;
	/** UUID of the source associated with the scene item */
	sourceUuid: string;
};

/** Gets the source associated with a scene item. */
export const GetSceneItemSource: ObsRequest<
	GetSceneItemSourceRequest,
	GetSceneItemSourceResponse
> = new ObsRequest<GetSceneItemSourceRequest, GetSceneItemSourceResponse>(
	"GetSceneItemSource",
);

/** Request for {@link GetSceneItemTransform} */
export type GetSceneItemTransformRequest = {
	/** Name of the scene the item is in */
	sceneName?: string;
	/** UUID of the scene the item is in */
	sceneUuid?: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
};

/** Response for {@link GetSceneItemTransform} */
export type GetSceneItemTransformResponse = {
	/** Object containing scene item transform info */
	sceneItemTransform: object;
};

/** Gets the transform and crop info of a scene item.

Scenes and Groups */
export const GetSceneItemTransform: ObsRequest<
	GetSceneItemTransformRequest,
	GetSceneItemTransformResponse
> = new ObsRequest<GetSceneItemTransformRequest, GetSceneItemTransformResponse>(
	"GetSceneItemTransform",
);

/** Response for {@link GetSceneList} */
export type GetSceneListResponse = {
	/** Current program scene name. Can be `null` if internal state desync */
	currentProgramSceneName: string;
	/** Current program scene UUID. Can be `null` if internal state desync */
	currentProgramSceneUuid: string;
	/** Current preview scene name. `null` if not in studio mode */
	currentPreviewSceneName: string;
	/** Current preview scene UUID. `null` if not in studio mode */
	currentPreviewSceneUuid: string;
	/** Array of scenes */
	scenes: object[];
};

/** Gets an array of all scenes in OBS. */
export const GetSceneList: ObsRequest<undefined, GetSceneListResponse> =
	new ObsRequest<undefined, GetSceneListResponse>("GetSceneList");

/** Request for {@link GetSceneSceneTransitionOverride} */
export type GetSceneSceneTransitionOverrideRequest = {
	/** Name of the scene */
	sceneName?: string;
	/** UUID of the scene */
	sceneUuid?: string;
};

/** Response for {@link GetSceneSceneTransitionOverride} */
export type GetSceneSceneTransitionOverrideResponse = {
	/** Name of the overridden scene transition, else `null` */
	transitionName: string;
	/** Duration of the overridden scene transition, else `null` */
	transitionDuration: number;
};

/** Gets the scene transition overridden for a scene.

Note: A transition UUID response field is not currently able to be implemented as of 2024-1-18. */
export const GetSceneSceneTransitionOverride: ObsRequest<
	GetSceneSceneTransitionOverrideRequest,
	GetSceneSceneTransitionOverrideResponse
> = new ObsRequest<
	GetSceneSceneTransitionOverrideRequest,
	GetSceneSceneTransitionOverrideResponse
>("GetSceneSceneTransitionOverride");

/** Response for {@link GetSceneTransitionList} */
export type GetSceneTransitionListResponse = {
	/** Name of the current scene transition. Can be null */
	currentSceneTransitionName: string;
	/** UUID of the current scene transition. Can be null */
	currentSceneTransitionUuid: string;
	/** Kind of the current scene transition. Can be null */
	currentSceneTransitionKind: string;
	/** Array of transitions */
	transitions: object[];
};

/** Gets an array of all scene transitions in OBS. */
export const GetSceneTransitionList: ObsRequest<
	undefined,
	GetSceneTransitionListResponse
> = new ObsRequest<undefined, GetSceneTransitionListResponse>(
	"GetSceneTransitionList",
);

/** Request for {@link GetSourceActive} */
export type GetSourceActiveRequest = {
	/** Name of the source to get the active state of */
	sourceName?: string;
	/** UUID of the source to get the active state of */
	sourceUuid?: string;
};

/** Response for {@link GetSourceActive} */
export type GetSourceActiveResponse = {
	/** Whether the source is showing in Program */
	videoActive: boolean;
	/** Whether the source is showing in the UI (Preview, Projector, Properties) */
	videoShowing: boolean;
};

/** Gets the active and show state of a source.

**Compatible with inputs and scenes.** */
export const GetSourceActive: ObsRequest<
	GetSourceActiveRequest,
	GetSourceActiveResponse
> = new ObsRequest<GetSourceActiveRequest, GetSourceActiveResponse>(
	"GetSourceActive",
);

/** Request for {@link GetSourceFilter} */
export type GetSourceFilterRequest = {
	/** Name of the source */
	sourceName?: string;
	/** UUID of the source */
	sourceUuid?: string;
	/** Name of the filter */
	filterName: string;
};

/** Response for {@link GetSourceFilter} */
export type GetSourceFilterResponse = {
	/** Whether the filter is enabled */
	filterEnabled: boolean;
	/** Index of the filter in the list, beginning at 0 */
	filterIndex: number;
	/** The kind of filter */
	filterKind: string;
	/** Settings object associated with the filter */
	filterSettings: object;
};

/** Gets the info for a specific source filter. */
export const GetSourceFilter: ObsRequest<
	GetSourceFilterRequest,
	GetSourceFilterResponse
> = new ObsRequest<GetSourceFilterRequest, GetSourceFilterResponse>(
	"GetSourceFilter",
);

/** Request for {@link GetSourceFilterDefaultSettings} */
export type GetSourceFilterDefaultSettingsRequest = {
	/** Filter kind to get the default settings for */
	filterKind: string;
};

/** Response for {@link GetSourceFilterDefaultSettings} */
export type GetSourceFilterDefaultSettingsResponse = {
	/** Object of default settings for the filter kind */
	defaultFilterSettings: object;
};

/** Gets the default settings for a filter kind. */
export const GetSourceFilterDefaultSettings: ObsRequest<
	GetSourceFilterDefaultSettingsRequest,
	GetSourceFilterDefaultSettingsResponse
> = new ObsRequest<
	GetSourceFilterDefaultSettingsRequest,
	GetSourceFilterDefaultSettingsResponse
>("GetSourceFilterDefaultSettings");

/** Response for {@link GetSourceFilterKindList} */
export type GetSourceFilterKindListResponse = {
	/** Array of source filter kinds */
	sourceFilterKinds: string[];
};

/** Gets an array of all available source filter kinds.

Similar to `GetInputKindList` */
export const GetSourceFilterKindList: ObsRequest<
	undefined,
	GetSourceFilterKindListResponse
> = new ObsRequest<undefined, GetSourceFilterKindListResponse>(
	"GetSourceFilterKindList",
);

/** Request for {@link GetSourceFilterList} */
export type GetSourceFilterListRequest = {
	/** Name of the source */
	sourceName?: string;
	/** UUID of the source */
	sourceUuid?: string;
};

/** Response for {@link GetSourceFilterList} */
export type GetSourceFilterListResponse = {
	/** Array of filters */
	filters: object[];
};

/** Gets an array of all of a source's filters. */
export const GetSourceFilterList: ObsRequest<
	GetSourceFilterListRequest,
	GetSourceFilterListResponse
> = new ObsRequest<GetSourceFilterListRequest, GetSourceFilterListResponse>(
	"GetSourceFilterList",
);

/** Request for {@link GetSourceScreenshot} */
export type GetSourceScreenshotRequest = {
	/** Name of the source to take a screenshot of */
	sourceName?: string;
	/** UUID of the source to take a screenshot of */
	sourceUuid?: string;
	/** Image compression format to use. Use `GetVersion` to get compatible image formats */
	imageFormat: string;
	/** Width to scale the screenshot to */
	imageWidth?: number;
	/** Height to scale the screenshot to */
	imageHeight?: number;
	/** Compression quality to use. 0 for high compression, 100 for uncompressed. -1 to use "default" (whatever that means, idk) */
	imageCompressionQuality?: number;
};

/** Response for {@link GetSourceScreenshot} */
export type GetSourceScreenshotResponse = {
	/** Base64-encoded screenshot */
	imageData: string;
};

/** Gets a Base64-encoded screenshot of a source.

The `imageWidth` and `imageHeight` parameters are treated as "scale to inner", meaning the smallest ratio will be used and the aspect ratio of the original resolution is kept.
If `imageWidth` and `imageHeight` are not specified, the compressed image will use the full resolution of the source.

**Compatible with inputs and scenes.** */
export const GetSourceScreenshot: ObsRequest<
	GetSourceScreenshotRequest,
	GetSourceScreenshotResponse
> = new ObsRequest<GetSourceScreenshotRequest, GetSourceScreenshotResponse>(
	"GetSourceScreenshot",
);

/** Response for {@link GetSpecialInputs} */
export type GetSpecialInputsResponse = {
	/** Name of the Desktop Audio input */
	desktop1: string;
	/** Name of the Desktop Audio 2 input */
	desktop2: string;
	/** Name of the Mic/Auxiliary Audio input */
	mic1: string;
	/** Name of the Mic/Auxiliary Audio 2 input */
	mic2: string;
	/** Name of the Mic/Auxiliary Audio 3 input */
	mic3: string;
	/** Name of the Mic/Auxiliary Audio 4 input */
	mic4: string;
};

/** Gets the names of all special inputs. */
export const GetSpecialInputs: ObsRequest<undefined, GetSpecialInputsResponse> =
	new ObsRequest<undefined, GetSpecialInputsResponse>("GetSpecialInputs");

/** Response for {@link GetStats} */
export type GetStatsResponse = {
	/** Current CPU usage in percent */
	cpuUsage: number;
	/** Amount of memory in MB currently being used by OBS */
	memoryUsage: number;
	/** Available disk space on the device being used for recording storage */
	availableDiskSpace: number;
	/** Current FPS being rendered */
	activeFps: number;
	/** Average time in milliseconds that OBS is taking to render a frame */
	averageFrameRenderTime: number;
	/** Number of frames skipped by OBS in the render thread */
	renderSkippedFrames: number;
	/** Total number of frames outputted by the render thread */
	renderTotalFrames: number;
	/** Number of frames skipped by OBS in the output thread */
	outputSkippedFrames: number;
	/** Total number of frames outputted by the output thread */
	outputTotalFrames: number;
	/** Total number of messages received by obs-websocket from the client */
	webSocketSessionIncomingMessages: number;
	/** Total number of messages sent by obs-websocket to the client */
	webSocketSessionOutgoingMessages: number;
};

/** Gets statistics about OBS, obs-websocket, and the current session. */
export const GetStats: ObsRequest<undefined, GetStatsResponse> = new ObsRequest<
	undefined,
	GetStatsResponse
>("GetStats");

/** Response for {@link GetStreamServiceSettings} */
export type GetStreamServiceSettingsResponse = {
	/** Stream service type, like `rtmp_custom` or `rtmp_common` */
	streamServiceType: string;
	/** Stream service settings */
	streamServiceSettings: object;
};

/** Gets the current stream service settings (stream destination). */
export const GetStreamServiceSettings: ObsRequest<
	undefined,
	GetStreamServiceSettingsResponse
> = new ObsRequest<undefined, GetStreamServiceSettingsResponse>(
	"GetStreamServiceSettings",
);

/** Response for {@link GetStreamStatus} */
export type GetStreamStatusResponse = {
	/** Whether the output is active */
	outputActive: boolean;
	/** Whether the output is currently reconnecting */
	outputReconnecting: boolean;
	/** Current formatted timecode string for the output */
	outputTimecode: string;
	/** Current duration in milliseconds for the output */
	outputDuration: number;
	/** Congestion of the output */
	outputCongestion: number;
	/** Number of bytes sent by the output */
	outputBytes: number;
	/** Number of frames skipped by the output's process */
	outputSkippedFrames: number;
	/** Total number of frames delivered by the output's process */
	outputTotalFrames: number;
};

/** Gets the status of the stream output. */
export const GetStreamStatus: ObsRequest<undefined, GetStreamStatusResponse> =
	new ObsRequest<undefined, GetStreamStatusResponse>("GetStreamStatus");

/** Response for {@link GetStudioModeEnabled} */
export type GetStudioModeEnabledResponse = {
	/** Whether studio mode is enabled */
	studioModeEnabled: boolean;
};

/** Gets whether studio is enabled. */
export const GetStudioModeEnabled: ObsRequest<
	undefined,
	GetStudioModeEnabledResponse
> = new ObsRequest<undefined, GetStudioModeEnabledResponse>(
	"GetStudioModeEnabled",
);

/** Response for {@link GetTransitionKindList} */
export type GetTransitionKindListResponse = {
	/** Array of transition kinds */
	transitionKinds: string[];
};

/** Gets an array of all available transition kinds.

Similar to `GetInputKindList` */
export const GetTransitionKindList: ObsRequest<
	undefined,
	GetTransitionKindListResponse
> = new ObsRequest<undefined, GetTransitionKindListResponse>(
	"GetTransitionKindList",
);

/** Response for {@link GetVersion} */
export type GetVersionResponse = {
	/** Current OBS Studio version */
	obsVersion: string;
	/** Current obs-websocket version */
	obsWebSocketVersion: string;
	/** Current latest obs-websocket RPC version */
	rpcVersion: number;
	/** Array of available RPC requests for the currently negotiated RPC version */
	availableRequests: string[];
	/** Image formats available in `GetSourceScreenshot` and `SaveSourceScreenshot` requests. */
	supportedImageFormats: string[];
	/** Name of the platform. Usually `windows`, `macos`, or `ubuntu` (linux flavor). Not guaranteed to be any of those */
	platform: string;
	/** Description of the platform, like `Windows 10 (10.0)` */
	platformDescription: string;
};

/** Gets data about the current plugin and RPC version. */
export const GetVersion: ObsRequest<undefined, GetVersionResponse> =
	new ObsRequest<undefined, GetVersionResponse>("GetVersion");

/** Response for {@link GetVideoSettings} */
export type GetVideoSettingsResponse = {
	/** Numerator of the fractional FPS value */
	fpsNumerator: number;
	/** Denominator of the fractional FPS value */
	fpsDenominator: number;
	/** Width of the base (canvas) resolution in pixels */
	baseWidth: number;
	/** Height of the base (canvas) resolution in pixels */
	baseHeight: number;
	/** Width of the output resolution in pixels */
	outputWidth: number;
	/** Height of the output resolution in pixels */
	outputHeight: number;
};

/** Gets the current video settings.

Note: To get the true FPS value, divide the FPS numerator by the FPS denominator. Example: `60000/1001` */
export const GetVideoSettings: ObsRequest<undefined, GetVideoSettingsResponse> =
	new ObsRequest<undefined, GetVideoSettingsResponse>("GetVideoSettings");

/** Response for {@link GetVirtualCamStatus} */
export type GetVirtualCamStatusResponse = {
	/** Whether the output is active */
	outputActive: boolean;
};

/** Gets the status of the virtualcam output. */
export const GetVirtualCamStatus: ObsRequest<
	undefined,
	GetVirtualCamStatusResponse
> = new ObsRequest<undefined, GetVirtualCamStatusResponse>(
	"GetVirtualCamStatus",
);

/** Request for {@link OffsetMediaInputCursor} */
export type OffsetMediaInputCursorRequest = {
	/** Name of the media input */
	inputName?: string;
	/** UUID of the media input */
	inputUuid?: string;
	/** Value to offset the current cursor position by */
	mediaCursorOffset: number;
};

/** Offsets the current cursor position of a media input by the specified value.

This request does not perform bounds checking of the cursor position. */
export const OffsetMediaInputCursor: ObsRequest<
	OffsetMediaInputCursorRequest,
	undefined
> = new ObsRequest<OffsetMediaInputCursorRequest, undefined>(
	"OffsetMediaInputCursor",
);

/** Request for {@link OpenInputFiltersDialog} */
export type OpenInputFiltersDialogRequest = {
	/** Name of the input to open the dialog of */
	inputName?: string;
	/** UUID of the input to open the dialog of */
	inputUuid?: string;
};

/** Opens the filters dialog of an input. */
export const OpenInputFiltersDialog: ObsRequest<
	OpenInputFiltersDialogRequest,
	undefined
> = new ObsRequest<OpenInputFiltersDialogRequest, undefined>(
	"OpenInputFiltersDialog",
);

/** Request for {@link OpenInputInteractDialog} */
export type OpenInputInteractDialogRequest = {
	/** Name of the input to open the dialog of */
	inputName?: string;
	/** UUID of the input to open the dialog of */
	inputUuid?: string;
};

/** Opens the interact dialog of an input. */
export const OpenInputInteractDialog: ObsRequest<
	OpenInputInteractDialogRequest,
	undefined
> = new ObsRequest<OpenInputInteractDialogRequest, undefined>(
	"OpenInputInteractDialog",
);

/** Request for {@link OpenInputPropertiesDialog} */
export type OpenInputPropertiesDialogRequest = {
	/** Name of the input to open the dialog of */
	inputName?: string;
	/** UUID of the input to open the dialog of */
	inputUuid?: string;
};

/** Opens the properties dialog of an input. */
export const OpenInputPropertiesDialog: ObsRequest<
	OpenInputPropertiesDialogRequest,
	undefined
> = new ObsRequest<OpenInputPropertiesDialogRequest, undefined>(
	"OpenInputPropertiesDialog",
);

/** Request for {@link OpenSourceProjector} */
export type OpenSourceProjectorRequest = {
	/** Name of the source to open a projector for */
	sourceName?: string;
	/** UUID of the source to open a projector for */
	sourceUuid?: string;
	/** Monitor index, use `GetMonitorList` to obtain index */
	monitorIndex?: number;
	/** Size/Position data for a windowed projector, in Qt Base64 encoded format. Mutually exclusive with `monitorIndex` */
	projectorGeometry?: string;
};

/** Opens a projector for a source.

Note: This request serves to provide feature parity with 4.x. It is very likely to be changed/deprecated in a future release. */
export const OpenSourceProjector: ObsRequest<
	OpenSourceProjectorRequest,
	undefined
> = new ObsRequest<OpenSourceProjectorRequest, undefined>(
	"OpenSourceProjector",
);

/** Request for {@link OpenVideoMixProjector} */
export type OpenVideoMixProjectorRequest = {
	/** Type of mix to open */
	videoMixType: string;
	/** Monitor index, use `GetMonitorList` to obtain index */
	monitorIndex?: number;
	/** Size/Position data for a windowed projector, in Qt Base64 encoded format. Mutually exclusive with `monitorIndex` */
	projectorGeometry?: string;
};

/** Opens a projector for a specific output video mix.

Mix types:

- `OBS_WEBSOCKET_VIDEO_MIX_TYPE_PREVIEW`
- `OBS_WEBSOCKET_VIDEO_MIX_TYPE_PROGRAM`
- `OBS_WEBSOCKET_VIDEO_MIX_TYPE_MULTIVIEW`

Note: This request serves to provide feature parity with 4.x. It is very likely to be changed/deprecated in a future release. */
export const OpenVideoMixProjector: ObsRequest<
	OpenVideoMixProjectorRequest,
	undefined
> = new ObsRequest<OpenVideoMixProjectorRequest, undefined>(
	"OpenVideoMixProjector",
);

/** Pauses the record output. */
export const PauseRecord: ObsRequest<undefined, undefined> = new ObsRequest<
	undefined,
	undefined
>("PauseRecord");

/** Request for {@link PressInputPropertiesButton} */
export type PressInputPropertiesButtonRequest = {
	/** Name of the input */
	inputName?: string;
	/** UUID of the input */
	inputUuid?: string;
	/** Name of the button property to press */
	propertyName: string;
};

/** Presses a button in the properties of an input.

Some known `propertyName` values are:

- `refreshnocache` - Browser source reload button

Note: Use this in cases where there is a button in the properties of an input that cannot be accessed in any other way. For example, browser sources, where there is a refresh button. */
export const PressInputPropertiesButton: ObsRequest<
	PressInputPropertiesButtonRequest,
	undefined
> = new ObsRequest<PressInputPropertiesButtonRequest, undefined>(
	"PressInputPropertiesButton",
);

/** Request for {@link RemoveInput} */
export type RemoveInputRequest = {
	/** Name of the input to remove */
	inputName?: string;
	/** UUID of the input to remove */
	inputUuid?: string;
};

/** Removes an existing input.

Note: Will immediately remove all associated scene items. */
export const RemoveInput: ObsRequest<RemoveInputRequest, undefined> =
	new ObsRequest<RemoveInputRequest, undefined>("RemoveInput");

/** Request for {@link RemoveProfile} */
export type RemoveProfileRequest = {
	/** Name of the profile to remove */
	profileName: string;
};

/** Removes a profile. If the current profile is chosen, it will change to a different profile first. */
export const RemoveProfile: ObsRequest<RemoveProfileRequest, undefined> =
	new ObsRequest<RemoveProfileRequest, undefined>("RemoveProfile");

/** Request for {@link RemoveScene} */
export type RemoveSceneRequest = {
	/** Name of the scene to remove */
	sceneName?: string;
	/** UUID of the scene to remove */
	sceneUuid?: string;
};

/** Removes a scene from OBS. */
export const RemoveScene: ObsRequest<RemoveSceneRequest, undefined> =
	new ObsRequest<RemoveSceneRequest, undefined>("RemoveScene");

/** Request for {@link RemoveSceneItem} */
export type RemoveSceneItemRequest = {
	/** Name of the scene the item is in */
	sceneName?: string;
	/** UUID of the scene the item is in */
	sceneUuid?: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
};

/** Removes a scene item from a scene.

Scenes only */
export const RemoveSceneItem: ObsRequest<RemoveSceneItemRequest, undefined> =
	new ObsRequest<RemoveSceneItemRequest, undefined>("RemoveSceneItem");

/** Request for {@link RemoveSourceFilter} */
export type RemoveSourceFilterRequest = {
	/** Name of the source the filter is on */
	sourceName?: string;
	/** UUID of the source the filter is on */
	sourceUuid?: string;
	/** Name of the filter to remove */
	filterName: string;
};

/** Removes a filter from a source. */
export const RemoveSourceFilter: ObsRequest<
	RemoveSourceFilterRequest,
	undefined
> = new ObsRequest<RemoveSourceFilterRequest, undefined>("RemoveSourceFilter");

/** Resumes the record output. */
export const ResumeRecord: ObsRequest<undefined, undefined> = new ObsRequest<
	undefined,
	undefined
>("ResumeRecord");

/** Saves the contents of the replay buffer output. */
export const SaveReplayBuffer: ObsRequest<undefined, undefined> =
	new ObsRequest<undefined, undefined>("SaveReplayBuffer");

/** Request for {@link SaveSourceScreenshot} */
export type SaveSourceScreenshotRequest = {
	/** Name of the source to take a screenshot of */
	sourceName?: string;
	/** UUID of the source to take a screenshot of */
	sourceUuid?: string;
	/** Image compression format to use. Use `GetVersion` to get compatible image formats */
	imageFormat: string;
	/** Path to save the screenshot file to. Eg. `C:\Users\user\Desktop\screenshot.png` */
	imageFilePath: string;
	/** Width to scale the screenshot to */
	imageWidth?: number;
	/** Height to scale the screenshot to */
	imageHeight?: number;
	/** Compression quality to use. 0 for high compression, 100 for uncompressed. -1 to use "default" (whatever that means, idk) */
	imageCompressionQuality?: number;
};

/** Saves a screenshot of a source to the filesystem.

The `imageWidth` and `imageHeight` parameters are treated as "scale to inner", meaning the smallest ratio will be used and the aspect ratio of the original resolution is kept.
If `imageWidth` and `imageHeight` are not specified, the compressed image will use the full resolution of the source.

**Compatible with inputs and scenes.** */
export const SaveSourceScreenshot: ObsRequest<
	SaveSourceScreenshotRequest,
	undefined
> = new ObsRequest<SaveSourceScreenshotRequest, undefined>(
	"SaveSourceScreenshot",
);

/** Request for {@link SendStreamCaption} */
export type SendStreamCaptionRequest = {
	/** Caption text */
	captionText: string;
};

/** Sends CEA-608 caption text over the stream output. */
export const SendStreamCaption: ObsRequest<
	SendStreamCaptionRequest,
	undefined
> = new ObsRequest<SendStreamCaptionRequest, undefined>("SendStreamCaption");

/** Request for {@link SetCurrentPreviewScene} */
export type SetCurrentPreviewSceneRequest = {
	/** Scene name to set as the current preview scene */
	sceneName?: string;
	/** Scene UUID to set as the current preview scene */
	sceneUuid?: string;
};

/** Sets the current preview scene.

Only available when studio mode is enabled. */
export const SetCurrentPreviewScene: ObsRequest<
	SetCurrentPreviewSceneRequest,
	undefined
> = new ObsRequest<SetCurrentPreviewSceneRequest, undefined>(
	"SetCurrentPreviewScene",
);

/** Request for {@link SetCurrentProfile} */
export type SetCurrentProfileRequest = {
	/** Name of the profile to switch to */
	profileName: string;
};

/** Switches to a profile. */
export const SetCurrentProfile: ObsRequest<
	SetCurrentProfileRequest,
	undefined
> = new ObsRequest<SetCurrentProfileRequest, undefined>("SetCurrentProfile");

/** Request for {@link SetCurrentProgramScene} */
export type SetCurrentProgramSceneRequest = {
	/** Scene name to set as the current program scene */
	sceneName?: string;
	/** Scene UUID to set as the current program scene */
	sceneUuid?: string;
};

/** Sets the current program scene. */
export const SetCurrentProgramScene: ObsRequest<
	SetCurrentProgramSceneRequest,
	undefined
> = new ObsRequest<SetCurrentProgramSceneRequest, undefined>(
	"SetCurrentProgramScene",
);

/** Request for {@link SetCurrentSceneCollection} */
export type SetCurrentSceneCollectionRequest = {
	/** Name of the scene collection to switch to */
	sceneCollectionName: string;
};

/** Switches to a scene collection.

Note: This will block until the collection has finished changing. */
export const SetCurrentSceneCollection: ObsRequest<
	SetCurrentSceneCollectionRequest,
	undefined
> = new ObsRequest<SetCurrentSceneCollectionRequest, undefined>(
	"SetCurrentSceneCollection",
);

/** Request for {@link SetCurrentSceneTransition} */
export type SetCurrentSceneTransitionRequest = {
	/** Name of the transition to make active */
	transitionName: string;
};

/** Sets the current scene transition.

Small note: While the namespace of scene transitions is generally unique, that uniqueness is not a guarantee as it is with other resources like inputs. */
export const SetCurrentSceneTransition: ObsRequest<
	SetCurrentSceneTransitionRequest,
	undefined
> = new ObsRequest<SetCurrentSceneTransitionRequest, undefined>(
	"SetCurrentSceneTransition",
);

/** Request for {@link SetCurrentSceneTransitionDuration} */
export type SetCurrentSceneTransitionDurationRequest = {
	/** Duration in milliseconds */
	transitionDuration: number;
};

/** Sets the duration of the current scene transition, if it is not fixed. */
export const SetCurrentSceneTransitionDuration: ObsRequest<
	SetCurrentSceneTransitionDurationRequest,
	undefined
> = new ObsRequest<SetCurrentSceneTransitionDurationRequest, undefined>(
	"SetCurrentSceneTransitionDuration",
);

/** Request for {@link SetCurrentSceneTransitionSettings} */
export type SetCurrentSceneTransitionSettingsRequest = {
	/** Settings object to apply to the transition. Can be `{}` */
	transitionSettings: object;
	/** Whether to overlay over the current settings or replace them */
	overlay?: boolean;
};

/** Sets the settings of the current scene transition. */
export const SetCurrentSceneTransitionSettings: ObsRequest<
	SetCurrentSceneTransitionSettingsRequest,
	undefined
> = new ObsRequest<SetCurrentSceneTransitionSettingsRequest, undefined>(
	"SetCurrentSceneTransitionSettings",
);

/** Request for {@link SetInputAudioBalance} */
export type SetInputAudioBalanceRequest = {
	/** Name of the input to set the audio balance of */
	inputName?: string;
	/** UUID of the input to set the audio balance of */
	inputUuid?: string;
	/** New audio balance value */
	inputAudioBalance: number;
};

/** Sets the audio balance of an input. */
export const SetInputAudioBalance: ObsRequest<
	SetInputAudioBalanceRequest,
	undefined
> = new ObsRequest<SetInputAudioBalanceRequest, undefined>(
	"SetInputAudioBalance",
);

/** Request for {@link SetInputAudioMonitorType} */
export type SetInputAudioMonitorTypeRequest = {
	/** Name of the input to set the audio monitor type of */
	inputName?: string;
	/** UUID of the input to set the audio monitor type of */
	inputUuid?: string;
	/** Audio monitor type */
	monitorType: string;
};

/** Sets the audio monitor type of an input. */
export const SetInputAudioMonitorType: ObsRequest<
	SetInputAudioMonitorTypeRequest,
	undefined
> = new ObsRequest<SetInputAudioMonitorTypeRequest, undefined>(
	"SetInputAudioMonitorType",
);

/** Request for {@link SetInputAudioSyncOffset} */
export type SetInputAudioSyncOffsetRequest = {
	/** Name of the input to set the audio sync offset of */
	inputName?: string;
	/** UUID of the input to set the audio sync offset of */
	inputUuid?: string;
	/** New audio sync offset in milliseconds */
	inputAudioSyncOffset: number;
};

/** Sets the audio sync offset of an input. */
export const SetInputAudioSyncOffset: ObsRequest<
	SetInputAudioSyncOffsetRequest,
	undefined
> = new ObsRequest<SetInputAudioSyncOffsetRequest, undefined>(
	"SetInputAudioSyncOffset",
);

/** Request for {@link SetInputAudioTracks} */
export type SetInputAudioTracksRequest = {
	/** Name of the input */
	inputName?: string;
	/** UUID of the input */
	inputUuid?: string;
	/** Track settings to apply */
	inputAudioTracks: object;
};

/** Sets the enable state of audio tracks of an input. */
export const SetInputAudioTracks: ObsRequest<
	SetInputAudioTracksRequest,
	undefined
> = new ObsRequest<SetInputAudioTracksRequest, undefined>(
	"SetInputAudioTracks",
);

/** Request for {@link SetInputDeinterlaceFieldOrder} */
export type SetInputDeinterlaceFieldOrderRequest = {
	/** Name of the input */
	inputName?: string;
	/** UUID of the input */
	inputUuid?: string;
	/** Deinterlace field order for the input */
	inputDeinterlaceFieldOrder: string;
};

/** Sets the deinterlace field order of an input.

Note: Deinterlacing functionality is restricted to async inputs only. */
export const SetInputDeinterlaceFieldOrder: ObsRequest<
	SetInputDeinterlaceFieldOrderRequest,
	undefined
> = new ObsRequest<SetInputDeinterlaceFieldOrderRequest, undefined>(
	"SetInputDeinterlaceFieldOrder",
);

/** Request for {@link SetInputDeinterlaceMode} */
export type SetInputDeinterlaceModeRequest = {
	/** Name of the input */
	inputName?: string;
	/** UUID of the input */
	inputUuid?: string;
	/** Deinterlace mode for the input */
	inputDeinterlaceMode: string;
};

/** Sets the deinterlace mode of an input.

Note: Deinterlacing functionality is restricted to async inputs only. */
export const SetInputDeinterlaceMode: ObsRequest<
	SetInputDeinterlaceModeRequest,
	undefined
> = new ObsRequest<SetInputDeinterlaceModeRequest, undefined>(
	"SetInputDeinterlaceMode",
);

/** Request for {@link SetInputMute} */
export type SetInputMuteRequest = {
	/** Name of the input to set the mute state of */
	inputName?: string;
	/** UUID of the input to set the mute state of */
	inputUuid?: string;
	/** Whether to mute the input or not */
	inputMuted: boolean;
};

/** Sets the audio mute state of an input. */
export const SetInputMute: ObsRequest<SetInputMuteRequest, undefined> =
	new ObsRequest<SetInputMuteRequest, undefined>("SetInputMute");

/** Request for {@link SetInputName} */
export type SetInputNameRequest = {
	/** Current input name */
	inputName?: string;
	/** Current input UUID */
	inputUuid?: string;
	/** New name for the input */
	newInputName: string;
};

/** Sets the name of an input (rename). */
export const SetInputName: ObsRequest<SetInputNameRequest, undefined> =
	new ObsRequest<SetInputNameRequest, undefined>("SetInputName");

/** Request for {@link SetInputSettings} */
export type SetInputSettingsRequest = {
	/** Name of the input to set the settings of */
	inputName?: string;
	/** UUID of the input to set the settings of */
	inputUuid?: string;
	/** Object of settings to apply */
	inputSettings: object;
	/** True == apply the settings on top of existing ones, False == reset the input to its defaults, then apply settings. */
	overlay?: boolean;
};

/** Sets the settings of an input. */
export const SetInputSettings: ObsRequest<SetInputSettingsRequest, undefined> =
	new ObsRequest<SetInputSettingsRequest, undefined>("SetInputSettings");

/** Request for {@link SetInputVolume} */
export type SetInputVolumeRequest = {
	/** Name of the input to set the volume of */
	inputName?: string;
	/** UUID of the input to set the volume of */
	inputUuid?: string;
	/** Volume setting in mul */
	inputVolumeMul?: number;
	/** Volume setting in dB */
	inputVolumeDb?: number;
};

/** Sets the volume setting of an input. */
export const SetInputVolume: ObsRequest<SetInputVolumeRequest, undefined> =
	new ObsRequest<SetInputVolumeRequest, undefined>("SetInputVolume");

/** Request for {@link SetMediaInputCursor} */
export type SetMediaInputCursorRequest = {
	/** Name of the media input */
	inputName?: string;
	/** UUID of the media input */
	inputUuid?: string;
	/** New cursor position to set */
	mediaCursor: number;
};

/** Sets the cursor position of a media input.

This request does not perform bounds checking of the cursor position. */
export const SetMediaInputCursor: ObsRequest<
	SetMediaInputCursorRequest,
	undefined
> = new ObsRequest<SetMediaInputCursorRequest, undefined>(
	"SetMediaInputCursor",
);

/** Request for {@link SetOutputSettings} */
export type SetOutputSettingsRequest = {
	/** Output name */
	outputName: string;
	/** Output settings */
	outputSettings: object;
};

/** Sets the settings of an output. */
export const SetOutputSettings: ObsRequest<
	SetOutputSettingsRequest,
	undefined
> = new ObsRequest<SetOutputSettingsRequest, undefined>("SetOutputSettings");

/** Request for {@link SetPersistentData} */
export type SetPersistentDataRequest = {
	/** The data realm to select. `OBS_WEBSOCKET_DATA_REALM_GLOBAL` or `OBS_WEBSOCKET_DATA_REALM_PROFILE` */
	realm: string;
	/** The name of the slot to retrieve data from */
	slotName: string;
	/** The value to apply to the slot */
	slotValue: unknown;
};

/** Sets the value of a "slot" from the selected persistent data realm. */
export const SetPersistentData: ObsRequest<
	SetPersistentDataRequest,
	undefined
> = new ObsRequest<SetPersistentDataRequest, undefined>("SetPersistentData");

/** Request for {@link SetProfileParameter} */
export type SetProfileParameterRequest = {
	/** Category of the parameter to set */
	parameterCategory: string;
	/** Name of the parameter to set */
	parameterName: string;
	/** Value of the parameter to set. Use `null` to delete */
	parameterValue: string;
};

/** Sets the value of a parameter in the current profile's configuration. */
export const SetProfileParameter: ObsRequest<
	SetProfileParameterRequest,
	undefined
> = new ObsRequest<SetProfileParameterRequest, undefined>(
	"SetProfileParameter",
);

/** Request for {@link SetRecordDirectory} */
export type SetRecordDirectoryRequest = {
	/** Output directory */
	recordDirectory: string;
};

/** Sets the current directory that the record output writes files to. */
export const SetRecordDirectory: ObsRequest<
	SetRecordDirectoryRequest,
	undefined
> = new ObsRequest<SetRecordDirectoryRequest, undefined>("SetRecordDirectory");

/** Request for {@link SetSceneItemBlendMode} */
export type SetSceneItemBlendModeRequest = {
	/** Name of the scene the item is in */
	sceneName?: string;
	/** UUID of the scene the item is in */
	sceneUuid?: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
	/** New blend mode */
	sceneItemBlendMode: string;
};

/** Sets the blend mode of a scene item.

Scenes and Groups */
export const SetSceneItemBlendMode: ObsRequest<
	SetSceneItemBlendModeRequest,
	undefined
> = new ObsRequest<SetSceneItemBlendModeRequest, undefined>(
	"SetSceneItemBlendMode",
);

/** Request for {@link SetSceneItemEnabled} */
export type SetSceneItemEnabledRequest = {
	/** Name of the scene the item is in */
	sceneName?: string;
	/** UUID of the scene the item is in */
	sceneUuid?: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
	/** New enable state of the scene item */
	sceneItemEnabled: boolean;
};

/** Sets the enable state of a scene item.

Scenes and Groups */
export const SetSceneItemEnabled: ObsRequest<
	SetSceneItemEnabledRequest,
	undefined
> = new ObsRequest<SetSceneItemEnabledRequest, undefined>(
	"SetSceneItemEnabled",
);

/** Request for {@link SetSceneItemIndex} */
export type SetSceneItemIndexRequest = {
	/** Name of the scene the item is in */
	sceneName?: string;
	/** UUID of the scene the item is in */
	sceneUuid?: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
	/** New index position of the scene item */
	sceneItemIndex: number;
};

/** Sets the index position of a scene item in a scene.

Scenes and Groups */
export const SetSceneItemIndex: ObsRequest<
	SetSceneItemIndexRequest,
	undefined
> = new ObsRequest<SetSceneItemIndexRequest, undefined>("SetSceneItemIndex");

/** Request for {@link SetSceneItemLocked} */
export type SetSceneItemLockedRequest = {
	/** Name of the scene the item is in */
	sceneName?: string;
	/** UUID of the scene the item is in */
	sceneUuid?: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
	/** New lock state of the scene item */
	sceneItemLocked: boolean;
};

/** Sets the lock state of a scene item.

Scenes and Group */
export const SetSceneItemLocked: ObsRequest<
	SetSceneItemLockedRequest,
	undefined
> = new ObsRequest<SetSceneItemLockedRequest, undefined>("SetSceneItemLocked");

/** Request for {@link SetSceneItemTransform} */
export type SetSceneItemTransformRequest = {
	/** Name of the scene the item is in */
	sceneName?: string;
	/** UUID of the scene the item is in */
	sceneUuid?: string;
	/** Numeric ID of the scene item */
	sceneItemId: number;
	/** Object containing scene item transform info to update */
	sceneItemTransform: object;
};

/** Sets the transform and crop info of a scene item. */
export const SetSceneItemTransform: ObsRequest<
	SetSceneItemTransformRequest,
	undefined
> = new ObsRequest<SetSceneItemTransformRequest, undefined>(
	"SetSceneItemTransform",
);

/** Request for {@link SetSceneName} */
export type SetSceneNameRequest = {
	/** Name of the scene to be renamed */
	sceneName?: string;
	/** UUID of the scene to be renamed */
	sceneUuid?: string;
	/** New name for the scene */
	newSceneName: string;
};

/** Sets the name of a scene (rename). */
export const SetSceneName: ObsRequest<SetSceneNameRequest, undefined> =
	new ObsRequest<SetSceneNameRequest, undefined>("SetSceneName");

/** Request for {@link SetSceneSceneTransitionOverride} */
export type SetSceneSceneTransitionOverrideRequest = {
	/** Name of the scene */
	sceneName?: string;
	/** UUID of the scene */
	sceneUuid?: string;
	/** Name of the scene transition to use as override. Specify `null` to remove */
	transitionName?: string;
	/** Duration to use for any overridden transition. Specify `null` to remove */
	transitionDuration?: number;
};

/** Sets the scene transition overridden for a scene. */
export const SetSceneSceneTransitionOverride: ObsRequest<
	SetSceneSceneTransitionOverrideRequest,
	undefined
> = new ObsRequest<SetSceneSceneTransitionOverrideRequest, undefined>(
	"SetSceneSceneTransitionOverride",
);

/** Request for {@link SetSourceFilterEnabled} */
export type SetSourceFilterEnabledRequest = {
	/** Name of the source the filter is on */
	sourceName?: string;
	/** UUID of the source the filter is on */
	sourceUuid?: string;
	/** Name of the filter */
	filterName: string;
	/** New enable state of the filter */
	filterEnabled: boolean;
};

/** Sets the enable state of a source filter. */
export const SetSourceFilterEnabled: ObsRequest<
	SetSourceFilterEnabledRequest,
	undefined
> = new ObsRequest<SetSourceFilterEnabledRequest, undefined>(
	"SetSourceFilterEnabled",
);

/** Request for {@link SetSourceFilterIndex} */
export type SetSourceFilterIndexRequest = {
	/** Name of the source the filter is on */
	sourceName?: string;
	/** UUID of the source the filter is on */
	sourceUuid?: string;
	/** Name of the filter */
	filterName: string;
	/** New index position of the filter */
	filterIndex: number;
};

/** Sets the index position of a filter on a source. */
export const SetSourceFilterIndex: ObsRequest<
	SetSourceFilterIndexRequest,
	undefined
> = new ObsRequest<SetSourceFilterIndexRequest, undefined>(
	"SetSourceFilterIndex",
);

/** Request for {@link SetSourceFilterName} */
export type SetSourceFilterNameRequest = {
	/** Name of the source the filter is on */
	sourceName?: string;
	/** UUID of the source the filter is on */
	sourceUuid?: string;
	/** Current name of the filter */
	filterName: string;
	/** New name for the filter */
	newFilterName: string;
};

/** Sets the name of a source filter (rename). */
export const SetSourceFilterName: ObsRequest<
	SetSourceFilterNameRequest,
	undefined
> = new ObsRequest<SetSourceFilterNameRequest, undefined>(
	"SetSourceFilterName",
);

/** Request for {@link SetSourceFilterSettings} */
export type SetSourceFilterSettingsRequest = {
	/** Name of the source the filter is on */
	sourceName?: string;
	/** UUID of the source the filter is on */
	sourceUuid?: string;
	/** Name of the filter to set the settings of */
	filterName: string;
	/** Object of settings to apply */
	filterSettings: object;
	/** True == apply the settings on top of existing ones, False == reset the input to its defaults, then apply settings. */
	overlay?: boolean;
};

/** Sets the settings of a source filter. */
export const SetSourceFilterSettings: ObsRequest<
	SetSourceFilterSettingsRequest,
	undefined
> = new ObsRequest<SetSourceFilterSettingsRequest, undefined>(
	"SetSourceFilterSettings",
);

/** Request for {@link SetStreamServiceSettings} */
export type SetStreamServiceSettingsRequest = {
	/** Type of stream service to apply. Example: `rtmp_common` or `rtmp_custom` */
	streamServiceType: string;
	/** Settings to apply to the service */
	streamServiceSettings: object;
};

/** Sets the current stream service settings (stream destination).

Note: Simple RTMP settings can be set with type `rtmp_custom` and the settings fields `server` and `key`. */
export const SetStreamServiceSettings: ObsRequest<
	SetStreamServiceSettingsRequest,
	undefined
> = new ObsRequest<SetStreamServiceSettingsRequest, undefined>(
	"SetStreamServiceSettings",
);

/** Request for {@link SetStudioModeEnabled} */
export type SetStudioModeEnabledRequest = {
	/** True == Enabled, False == Disabled */
	studioModeEnabled: boolean;
};

/** Enables or disables studio mode */
export const SetStudioModeEnabled: ObsRequest<
	SetStudioModeEnabledRequest,
	undefined
> = new ObsRequest<SetStudioModeEnabledRequest, undefined>(
	"SetStudioModeEnabled",
);

/** Request for {@link SetTBarPosition} */
export type SetTBarPositionRequest = {
	/** New position */
	position: number;
	/** Whether to release the TBar. Only set `false` if you know that you will be sending another position update */
	release?: boolean;
};

/** Sets the position of the TBar.

**Very important note**: This will be deprecated and replaced in a future version of obs-websocket. */
export const SetTBarPosition: ObsRequest<SetTBarPositionRequest, undefined> =
	new ObsRequest<SetTBarPositionRequest, undefined>("SetTBarPosition");

/** Request for {@link SetVideoSettings} */
export type SetVideoSettingsRequest = {
	/** Numerator of the fractional FPS value */
	fpsNumerator?: number;
	/** Denominator of the fractional FPS value */
	fpsDenominator?: number;
	/** Width of the base (canvas) resolution in pixels */
	baseWidth?: number;
	/** Height of the base (canvas) resolution in pixels */
	baseHeight?: number;
	/** Width of the output resolution in pixels */
	outputWidth?: number;
	/** Height of the output resolution in pixels */
	outputHeight?: number;
};

/** Sets the current video settings.

Note: Fields must be specified in pairs. For example, you cannot set only `baseWidth` without needing to specify `baseHeight`. */
export const SetVideoSettings: ObsRequest<SetVideoSettingsRequest, undefined> =
	new ObsRequest<SetVideoSettingsRequest, undefined>("SetVideoSettings");

/** Request for {@link Sleep} */
export type SleepRequest = {
	/** Number of milliseconds to sleep for (if `SERIAL_REALTIME` mode) */
	sleepMillis?: number;
	/** Number of frames to sleep for (if `SERIAL_FRAME` mode) */
	sleepFrames?: number;
};

/** Sleeps for a time duration or number of frames. Only available in request batches with types `SERIAL_REALTIME` or `SERIAL_FRAME`. */
export const Sleep: ObsRequest<SleepRequest, undefined> = new ObsRequest<
	SleepRequest,
	undefined
>("Sleep");

/** Splits the current file being recorded into a new file. */
export const SplitRecordFile: ObsRequest<undefined, undefined> = new ObsRequest<
	undefined,
	undefined
>("SplitRecordFile");

/** Request for {@link StartOutput} */
export type StartOutputRequest = {
	/** Output name */
	outputName: string;
};

/** Starts an output. */
export const StartOutput: ObsRequest<StartOutputRequest, undefined> =
	new ObsRequest<StartOutputRequest, undefined>("StartOutput");

/** Starts the record output. */
export const StartRecord: ObsRequest<undefined, undefined> = new ObsRequest<
	undefined,
	undefined
>("StartRecord");

/** Starts the replay buffer output. */
export const StartReplayBuffer: ObsRequest<undefined, undefined> =
	new ObsRequest<undefined, undefined>("StartReplayBuffer");

/** Starts the stream output. */
export const StartStream: ObsRequest<undefined, undefined> = new ObsRequest<
	undefined,
	undefined
>("StartStream");

/** Starts the virtualcam output. */
export const StartVirtualCam: ObsRequest<undefined, undefined> = new ObsRequest<
	undefined,
	undefined
>("StartVirtualCam");

/** Request for {@link StopOutput} */
export type StopOutputRequest = {
	/** Output name */
	outputName: string;
};

/** Stops an output. */
export const StopOutput: ObsRequest<StopOutputRequest, undefined> =
	new ObsRequest<StopOutputRequest, undefined>("StopOutput");

/** Response for {@link StopRecord} */
export type StopRecordResponse = {
	/** File name for the saved recording */
	outputPath: string;
};

/** Stops the record output. */
export const StopRecord: ObsRequest<undefined, StopRecordResponse> =
	new ObsRequest<undefined, StopRecordResponse>("StopRecord");

/** Stops the replay buffer output. */
export const StopReplayBuffer: ObsRequest<undefined, undefined> =
	new ObsRequest<undefined, undefined>("StopReplayBuffer");

/** Stops the stream output. */
export const StopStream: ObsRequest<undefined, undefined> = new ObsRequest<
	undefined,
	undefined
>("StopStream");

/** Stops the virtualcam output. */
export const StopVirtualCam: ObsRequest<undefined, undefined> = new ObsRequest<
	undefined,
	undefined
>("StopVirtualCam");

/** Request for {@link ToggleInputMute} */
export type ToggleInputMuteRequest = {
	/** Name of the input to toggle the mute state of */
	inputName?: string;
	/** UUID of the input to toggle the mute state of */
	inputUuid?: string;
};

/** Response for {@link ToggleInputMute} */
export type ToggleInputMuteResponse = {
	/** Whether the input has been muted or unmuted */
	inputMuted: boolean;
};

/** Toggles the audio mute state of an input. */
export const ToggleInputMute: ObsRequest<
	ToggleInputMuteRequest,
	ToggleInputMuteResponse
> = new ObsRequest<ToggleInputMuteRequest, ToggleInputMuteResponse>(
	"ToggleInputMute",
);

/** Request for {@link ToggleOutput} */
export type ToggleOutputRequest = {
	/** Output name */
	outputName: string;
};

/** Response for {@link ToggleOutput} */
export type ToggleOutputResponse = {
	/** Whether the output is active */
	outputActive: boolean;
};

/** Toggles the status of an output. */
export const ToggleOutput: ObsRequest<
	ToggleOutputRequest,
	ToggleOutputResponse
> = new ObsRequest<ToggleOutputRequest, ToggleOutputResponse>("ToggleOutput");

/** Response for {@link ToggleRecord} */
export type ToggleRecordResponse = {
	/** The new active state of the output */
	outputActive: boolean;
};

/** Toggles the status of the record output. */
export const ToggleRecord: ObsRequest<undefined, ToggleRecordResponse> =
	new ObsRequest<undefined, ToggleRecordResponse>("ToggleRecord");

/** Toggles pause on the record output. */
export const ToggleRecordPause: ObsRequest<undefined, undefined> =
	new ObsRequest<undefined, undefined>("ToggleRecordPause");

/** Response for {@link ToggleReplayBuffer} */
export type ToggleReplayBufferResponse = {
	/** Whether the output is active */
	outputActive: boolean;
};

/** Toggles the state of the replay buffer output. */
export const ToggleReplayBuffer: ObsRequest<
	undefined,
	ToggleReplayBufferResponse
> = new ObsRequest<undefined, ToggleReplayBufferResponse>("ToggleReplayBuffer");

/** Response for {@link ToggleStream} */
export type ToggleStreamResponse = {
	/** New state of the stream output */
	outputActive: boolean;
};

/** Toggles the status of the stream output. */
export const ToggleStream: ObsRequest<undefined, ToggleStreamResponse> =
	new ObsRequest<undefined, ToggleStreamResponse>("ToggleStream");

/** Response for {@link ToggleVirtualCam} */
export type ToggleVirtualCamResponse = {
	/** Whether the output is active */
	outputActive: boolean;
};

/** Toggles the state of the virtualcam output. */
export const ToggleVirtualCam: ObsRequest<undefined, ToggleVirtualCamResponse> =
	new ObsRequest<undefined, ToggleVirtualCamResponse>("ToggleVirtualCam");

/** Request for {@link TriggerHotkeyByKeySequence} */
export type TriggerHotkeyByKeySequenceRequest = {
	/** The OBS key ID to use. See https://github.com/obsproject/obs-studio/blob/master/libobs/obs-hotkeys.h */
	keyId?: string;
	/** Object containing key modifiers to apply */
	keyModifiers?: {
		/** Press Shift */
		shift?: boolean;
		/** Press CTRL */
		control?: boolean;
		/** Press ALT */
		alt?: boolean;
		/** Press CMD (Mac) */
		command?: boolean;
	};
};

/** Triggers a hotkey using a sequence of keys.

Note: Hotkey functionality in obs-websocket comes as-is, and we do not guarantee support if things are broken. In 9/10 usages of hotkey requests, there exists a better, more reliable method via other requests. */
export const TriggerHotkeyByKeySequence: ObsRequest<
	TriggerHotkeyByKeySequenceRequest,
	undefined
> = new ObsRequest<TriggerHotkeyByKeySequenceRequest, undefined>(
	"TriggerHotkeyByKeySequence",
);

/** Request for {@link TriggerHotkeyByName} */
export type TriggerHotkeyByNameRequest = {
	/** Name of the hotkey to trigger */
	hotkeyName: string;
	/** Name of context of the hotkey to trigger */
	contextName?: string;
};

/** Triggers a hotkey using its name. See `GetHotkeyList`.

Note: Hotkey functionality in obs-websocket comes as-is, and we do not guarantee support if things are broken. In 9/10 usages of hotkey requests, there exists a better, more reliable method via other requests. */
export const TriggerHotkeyByName: ObsRequest<
	TriggerHotkeyByNameRequest,
	undefined
> = new ObsRequest<TriggerHotkeyByNameRequest, undefined>(
	"TriggerHotkeyByName",
);

/** Request for {@link TriggerMediaInputAction} */
export type TriggerMediaInputActionRequest = {
	/** Name of the media input */
	inputName?: string;
	/** UUID of the media input */
	inputUuid?: string;
	/** Identifier of the `ObsMediaInputAction` enum */
	mediaAction: string;
};

/** Triggers an action on a media input. */
export const TriggerMediaInputAction: ObsRequest<
	TriggerMediaInputActionRequest,
	undefined
> = new ObsRequest<TriggerMediaInputActionRequest, undefined>(
	"TriggerMediaInputAction",
);

/** Triggers the current scene transition. Same functionality as the `Transition` button in studio mode. */
export const TriggerStudioModeTransition: ObsRequest<undefined, undefined> =
	new ObsRequest<undefined, undefined>("TriggerStudioModeTransition");
